<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"><meta name="color-scheme" content="dark"><title>Verify Email — AI Hub</title><link rel="stylesheet" href="{{ asset('css/frontend/auth-unified.css') }}"></head>
<body><div class="auth-shell">
<section class="auth-hero is-login" aria-label="AI Hub email verification"><div class="auth-grid" aria-hidden="true"></div>
<a class="auth-brand" href="{{ route('home') }}"><span class="auth-logo"><svg viewBox="0 0 32 32" fill="none"><path d="M16 2.8 27.2 9.2v13.6L16 29.2 4.8 22.8V9.2L16 2.8Z" stroke="url(#g1)" stroke-width="2.1"/><path d="m16 8 6.6 3.8v8.4L16 24l-6.6-3.8v-8.4L16 8Z" stroke="url(#g2)" stroke-width="2.1"/><circle cx="16" cy="16" r="2.4" fill="#86A8FF"/><defs><linearGradient id="g1" x1="5" y1="4" x2="27" y2="27"><stop stop-color="#24B6FF"/><stop offset="1" stop-color="#B24EFF"/></linearGradient><linearGradient id="g2" x1="10" y1="9" x2="22" y2="23"><stop stop-color="#6BE7FF"/><stop offset="1" stop-color="#7955FF"/></linearGradient></defs></svg></span><span class="auth-brand-name">AI Hub</span></a>
<div class="auth-hero-copy"><span class="auth-kicker">One secure step</span><h1>Verify your email.<br><span class="auth-gradient-text">Unlock your AI Hub.</span></h1><p>Verification protects your account and activates saved items, community actions, personalized discovery, and intelligence email preferences.</p></div>
<div class="auth-feature-row" aria-hidden="true"><div class="auth-feature"><span class="auth-feature-icon">✓</span><b>Secure</b><span>Signed verification</span></div><div class="auth-feature"><span class="auth-feature-icon">✉</span><b>Email</b><span>Private confirmation</span></div><div class="auth-feature"><span class="auth-feature-icon">AI</span><b>Personalized</b><span>Your own AI Hub</span></div><div class="auth-feature"><span class="auth-feature-icon">↻</span><b>Resend</b><span>Fresh link anytime</span></div></div></section>
<main class="auth-panel"><a class="auth-home-link" href="{{ route('home') }}">← Back to AI Hub</a><section class="auth-card auth-recovery-card"><div class="auth-recovery-badge">@</div><h2>Check your inbox</h2><p class="auth-subtitle">We sent a verification link to <strong>{{ auth()->user()->email }}</strong>.</p>
@if(session('status')==='verification-link-sent')<div class="auth-alert success">A fresh verification link has been sent.</div>@endif
<div class="auth-recovery-note">Open the email and click “Verify email address”. If you do not see it, check Spam/Junk and then resend.</div>
<form method="POST" action="{{ route('verification.send') }}">@csrf<button class="auth-submit" type="submit"><span>Resend Verification Email</span><span>→</span></button></form>
<form method="POST" action="{{ route('logout') }}" style="margin-top:12px">@csrf<button class="auth-social" type="submit" style="width:100%;justify-content:center">Sign out</button></form>
</section></main></div></body></html>