@extends('layouts.admin')
@section('title', 'API Monitoring')
@section('content')
<x-page-header title="API Monitoring" subtitle="Connection health, latency and request/error telemetry" :breadcrumb="['System', 'API Monitoring']" />
@if(session('status'))<div class="alert alert-success" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
@if(session('error'))<div class="alert alert-danger" style="margin-bottom:16px;">{{ session('error') }}</div>@endif
@if(!$hasLogs)<div class="card card-pad" style="margin-bottom:18px;border-color:var(--warn);"><b>Migration required for telemetry</b><div class="cell-sub">Run <code>php artisan migrate</code> to create <code>api_request_logs</code>. Provider configuration is still visible below.</div></div>@endif
<div class="kpi-grid" style="grid-template-columns:repeat(4,1fr);"><x-kpi-card icon="send" label="Requests Today" value="{{ number_format($todayRequests) }}" /><x-kpi-card icon="triangle-alert" label="Failures Today" value="{{ number_format($todayFailures) }}" /><x-kpi-card icon="percent" label="Error Rate" value="{{ $errorRate }}%" /><x-kpi-card icon="timer" label="Avg Latency" value="{{ $avgLatency }} ms" /></div>
<div class="grid-4" style="margin:20px 0;">@foreach($providers as $provider)@php($tone=$provider['status']==='connected'?'pos':($provider['status']==='error'?'neg':($provider['status']==='ready'?'info':'neutral')))<div class="card card-pad"><div class="flex items-center justify-between"><div class="kpi-icon"><i data-lucide="{{ $provider['icon'] }}"></i></div><span class="badge badge-{{ $tone }}">{{ ucfirst($provider['status']) }}</span></div><b style="display:block;margin-top:12px;">{{ $provider['name'] }}</b><div class="cell-sub">{{ $provider['configured'] ? 'Credential configured' : $provider['key_name'].' missing' }}</div><div class="grid-2" style="gap:8px;margin-top:12px;"><div><div class="cell-sub">Today</div><b class="mono">{{ $provider['requests'] }}</b></div><div><div class="cell-sub">Avg latency</div><b class="mono">{{ $provider['avgLatency'] }}ms</b></div></div><form method="POST" action="{{ route('admin.system.api-monitoring.test',$provider['key']) }}" style="margin-top:14px;">@csrf<button class="btn btn-secondary btn-sm" style="width:100%;justify-content:center;" {{ !$provider['configured']?'disabled':'' }}><i data-lucide="plug-zap"></i> Test Connection</button></form></div>@endforeach</div>
<div class="grid-12"><div class="col-8 card card-pad"><div class="section-title">Requests · Last 7 Days</div><canvas id="apiChart" height="90"></canvas></div><div class="col-4 card"><div class="card-head"><h3>Recent API Events</h3></div><div style="max-height:330px;overflow:auto;">@forelse($recent as $log)<div style="padding:12px 16px;border-bottom:1px solid var(--border);"><div class="flex justify-between"><b style="font-size:12.5px;">{{ strtoupper($log->provider) }}</b><span class="badge {{ $log->successful?'badge-pos':'badge-neg' }}">{{ $log->status_code ?: 'ERR' }}</span></div><div class="cell-sub" style="margin-top:4px;">{{ $log->duration_ms }}ms · {{ $log->created_at->diffForHumans() }}</div></div>@empty<div class="text-sub" style="padding:28px;text-align:center;">No API telemetry yet. Run a connection test to create the first event.</div>@endforelse</div></div></div>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script><script>const t=@json($trend);new Chart(document.getElementById('apiChart'),{type:'bar',data:{labels:t.map(x=>x.label),datasets:[{label:'Successful',data:t.map(x=>x.success),backgroundColor:'rgba(52,211,153,.6)',borderRadius:4,stack:'a'},{label:'Errors',data:t.map(x=>x.failed),backgroundColor:'rgba(248,113,113,.7)',borderRadius:4,stack:'a'}]},options:{plugins:{legend:{labels:{color:'#9aa3b8',boxWidth:8,font:{size:11}}}},scales:{x:{grid:{display:false},ticks:{color:'#5c6580'}},y:{beginAtZero:true,grid:{color:'rgba(255,255,255,.04)'},ticks:{color:'#5c6580'}}}}});</script>@endpush
