@extends('layouts.admin')
@section('title', 'Backup Center')
@section('content')
<x-page-header title="Backup Center" subtitle="Create, download and retain protected local snapshots" :breadcrumb="['System', 'Backups']">
<x-slot:actions><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#createBackup"><i data-lucide="database-backup"></i> Create Backup</button></x-slot:actions></x-page-header>
@if(session('status'))<div class="alert alert-success" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
@if(session('error'))<div class="alert alert-danger" style="margin-bottom:16px;">{{ session('error') }}</div>@endif
<div class="kpi-grid" style="grid-template-columns:repeat(4,1fr);"><x-kpi-card icon="clock" label="Last Backup" value="{{ $lastBackup ? $lastBackup['created_at']->diffForHumans() : 'Never' }}" /><x-kpi-card icon="layers" label="Backup Count" value="{{ count($items) }}" /><x-kpi-card icon="hard-drive" label="Backup Storage" value="{{ number_format($totalBytes/1048576,1) }} MB" /><x-kpi-card icon="database" label="Disk Free" value="{{ number_format($freeBytes/1073741824,1) }} GB" /></div>
<div class="card card-pad" style="margin:20px 0;border-color:rgba(52,211,153,.25);"><div class="flex gap-12"><i data-lucide="shield-check" style="color:var(--pos);"></i><div><b>Safe backup policy</b><div class="cell-sub">This center creates archives and allows download/delete. Automatic restore is intentionally not exposed because restoring production data is destructive and should use a controlled maintenance procedure.</div></div></div></div>
<div class="card"><div class="card-head"><h3>Backup History</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Archive</th><th>Created</th><th>Size</th><th>Type</th><th>Status</th><th></th></tr></thead><tbody>@forelse($items as $backup)<tr><td><b class="mono" style="font-size:12px;">{{ $backup['name'] }}</b></td><td class="cell-sub">{{ $backup['created_at']->format('M j, Y · g:i A') }}</td><td class="mono">{{ $backup['size'] }}</td><td><span class="badge badge-neutral">{{ ucfirst($backup['type']) }}</span></td><td><span class="badge badge-pos">Completed</span></td><td><div class="flex gap-8"><a class="icon-btn" href="{{ route('admin.system.backups.download',$backup['name']) }}" title="Download"><i data-lucide="download" style="width:14px;"></i></a><form method="POST" action="{{ route('admin.system.backups.destroy',$backup['name']) }}" onsubmit="return confirm('Delete this backup archive?')">@csrf @method('DELETE')<button class="icon-btn" title="Delete"><i data-lucide="trash-2" style="width:14px;"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="text-sub" style="text-align:center;padding:36px;">No backup archives yet. Create a Database, Files or Full backup.</td></tr>@endforelse</tbody></table></div></div>
<div class="modal fade" id="createBackup" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content" style="background:var(--bg-elevated);border:1px solid var(--border);"><form method="POST" action="{{ route('admin.system.backups.store') }}">@csrf<div class="modal-head"><h3>Create Protected Backup</h3><button type="button" class="icon-btn" data-bs-dismiss="modal"><i data-lucide="x"></i></button></div><div class="modal-body"><label class="form-label">Backup Type</label><select class="select" name="type" style="width:100%;"><option value="full">Full — database + uploaded files</option><option value="database">Database only</option><option value="files">Uploaded files only</option></select><div class="cell-sub" style="margin-top:12px;">MySQL backups use <code>mysqldump</code>. On XAMPP Windows the service auto-detects <code>C:\xampp\mysql\bin\mysqldump.exe</code>; otherwise set <code>MYSQLDUMP_PATH</code> in .env.</div></div><div class="modal-foot"><button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary btn-sm"><i data-lucide="database-backup"></i> Create Backup</button></div></form></div></div></div>
@endsection
