@extends('layouts.admin')
@section('title','Email Deliveries')
@push('styles')<link rel="stylesheet" href="{{ asset('css/pages/administration.css') }}"><link rel="stylesheet" href="{{ asset('css/pages/final-polish.css') }}">@endpush
@section('content')
<div class="ad-page"><x-page-header title="Email Deliveries" subtitle="Queued lifecycle and AI intelligence email monitoring" :breadcrumb="['System','Email Deliveries']" />
<section class="ad-kpis">
<article class="ad-kpi"><span><i data-lucide="mail"></i></span><div><small>Total</small><strong>{{ number_format($stats['total']) }}</strong></div></article>
<article class="ad-kpi ad-kpi--violet"><span><i data-lucide="clock-3"></i></span><div><small>Queued</small><strong>{{ number_format($stats['queued']) }}</strong></div></article>
<article class="ad-kpi ad-kpi--green"><span><i data-lucide="circle-check"></i></span><div><small>Sent</small><strong>{{ number_format($stats['sent']) }}</strong></div></article>
<article class="ad-kpi"><span><i data-lucide="triangle-alert"></i></span><div><small>Failed</small><strong>{{ number_format($stats['failed']) }}</strong></div></article>
</section>
<form method="GET" class="card fp-filterbar"><input class="input" name="search" value="{{ request('search') }}" placeholder="Email or subject"><select class="select" name="status"><option value="">All statuses</option>@foreach(['queued','sent','failed'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst($s) }}</option>@endforeach</select><select class="select" name="category"><option value="">All categories</option>@foreach($categories as $c)<option value="{{ $c }}" @selected(request('category')===$c)>{{ \Illuminate\Support\Str::headline($c) }}</option>@endforeach</select><button class="btn btn-secondary"><i data-lucide="filter"></i>Apply</button></form>
<section class="card fp-table-card"><header class="fp-card-head"><div><span class="fp-eyebrow">Delivery Trail</span><h2>Subscriber email activity</h2><p>Duplicate-protected queue records for welcome, alerts and weekly digest emails.</p></div><span class="fp-count">{{ number_format($logs->total()) }} records</span></header>
<div class="table-wrap"><table class="data-table fp-table"><thead><tr><th>User</th><th>Category</th><th>Subject</th><th>Status</th><th>Queued</th><th>Completed</th></tr></thead><tbody>@forelse($logs as $log)<tr><td><strong>{{ $log->user?->email ?? 'Deleted user' }}</strong></td><td><span class="fp-action">{{ \Illuminate\Support\Str::headline($log->category) }}</span></td><td>{{ $log->subject }}@if($log->error)<small class="fp-muted">{{ \Illuminate\Support\Str::limit($log->error,120) }}</small>@endif</td><td>{{ ucfirst($log->status) }}</td><td><span class="fp-muted">{{ $log->queued_at?->format('M j, Y · H:i') ?? '—' }}</span></td><td><span class="fp-muted">{{ ($log->sent_at ?: $log->failed_at)?->format('M j, Y · H:i') ?? '—' }}</span></td></tr>@empty<tr><td colspan="6">No email delivery records yet.</td></tr>@endforelse</tbody></table></div><div class="fp-pagination"><span>Showing {{ $logs->firstItem()??0 }}–{{ $logs->lastItem()??0 }} of {{ $logs->total() }}</span><div>{{ $logs->links() }}</div></div></section></div>
@endsection