@extends('layouts.admin')
@section('title', 'Error Monitoring')
@section('content')
<x-page-header title="Error Monitoring" subtitle="Exception frequency, severity and resolution workflow" :breadcrumb="['System', 'Error Monitoring']" />
<div class="kpi-grid" style="grid-template-columns:repeat(5,1fr);"><x-kpi-card icon="alert-triangle" label="Total Groups" value="{{ $stats['total'] }}" /><x-kpi-card icon="octagon-alert" label="Critical" value="{{ $stats['critical'] }}" /><x-kpi-card icon="circle-dot" label="Open" value="{{ $stats['open'] }}" /><x-kpi-card icon="search-check" label="Investigating" value="{{ $stats['investigating'] }}" /><x-kpi-card icon="activity" label="Occurrences · 24h" value="{{ $stats['occurrences_24h'] }}" /></div>
<div class="grid-12" style="margin:20px 0;"><div class="col-8 card card-pad"><div class="section-title">Error Occurrences · 7 Days</div><canvas id="errorTrend" height="80"></canvas></div><div class="col-4 card card-pad"><div class="section-title">Resolution Health</div><div style="font-size:36px;font-weight:700;margin-top:14px;">{{ $stats['total'] ? round(($stats['resolved']/$stats['total'])*100) : 100 }}%</div><div class="cell-sub">of error groups resolved</div><div class="progress" style="margin-top:16px;"><span style="width:{{ $stats['total'] ? round(($stats['resolved']/$stats['total'])*100) : 100 }}%;"></span></div></div></div>
<form class="card card-pad" method="GET" style="margin-bottom:14px;"><div class="flex gap-8" style="flex-wrap:wrap;"><input class="input" name="q" value="{{ request('q') }}" placeholder="Search exception, message or URL" style="min-width:280px;"><select class="select" name="status"><option value="">All statuses</option>@foreach(['open','investigating','resolved'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst($s) }}</option>@endforeach</select><select class="select" name="severity"><option value="">All severities</option>@foreach(['critical','medium','low'] as $s)<option value="{{ $s }}" @selected(request('severity')===$s)>{{ ucfirst($s) }}</option>@endforeach</select><button class="btn btn-primary btn-sm">Filter</button><a class="btn btn-secondary btn-sm" href="{{ route('admin.system.errors.index') }}">Reset</a></div></form>
<div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Error</th><th>Location</th><th>Severity</th><th>Occurrences</th><th>Last Seen</th><th>Status</th><th></th></tr></thead><tbody>@forelse($errors as $error)<tr><td><b class="mono" style="font-size:12.5px;">{{ class_basename($error->exception_class) }}</b><div class="cell-sub" style="max-width:350px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">{{ $error->message }}</div></td><td class="cell-sub">{{ basename($error->file??'') }}:{{ $error->line }}</td><td><span class="badge badge-{{ $error->severity==='critical'?'neg':($error->severity==='medium'?'warn':'neutral') }}">{{ ucfirst($error->severity) }}</span></td><td>{{ number_format($error->occurrence_count) }}x</td><td class="cell-sub">{{ $error->last_seen_at->diffForHumans() }}</td><td><span class="badge badge-{{ $error->status==='resolved'?'pos':($error->status==='investigating'?'warn':'neg') }}">{{ ucfirst($error->status) }}</span></td><td><a class="btn btn-ghost btn-sm" href="{{ route('admin.system.errors.show',$error->id) }}">Investigate</a></td></tr>@empty<tr><td colspan="7" class="text-sub" style="padding:36px;text-align:center;">No matching errors found.</td></tr>@endforelse</tbody></table></div><div class="pager">{{ $errors->links() }}</div></div>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script><script>const e=@json($trend);new Chart(document.getElementById('errorTrend'),{type:'line',data:{labels:e.map(x=>x.label),datasets:[{label:'Occurrences',data:e.map(x=>x.count),borderColor:'rgba(248,113,113,.9)',backgroundColor:'rgba(248,113,113,.1)',fill:true,tension:.35}]},options:{plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:'#5c6580'}},y:{beginAtZero:true,grid:{color:'rgba(255,255,255,.04)'},ticks:{color:'#5c6580'}}}}});</script>@endpush
