@extends('layouts.admin')
@section('title','Notifications')
@push('styles')<link rel="stylesheet" href="{{ asset('css/pages/administration.css') }}">@endpush
@section('content')
@php $readCount=max(0,$notifications->total()-$unreadCount); @endphp
<div class="ad-page">
<x-page-header title="Notification Center" :subtitle="$unreadCount.' unread administrator notification(s)'" :breadcrumb="['System','Notifications']">
<x-slot:actions><a href="{{ route('admin.system.notification-rules') }}" class="btn btn-secondary"><i data-lucide="sliders-horizontal"></i>Alert Rules</a>@if($unreadCount)<form action="{{ route('admin.system.notifications.mark-all-read') }}" method="POST">@csrf<button class="btn btn-primary"><i data-lucide="check-check"></i>Mark All Read</button></form>@endif</x-slot:actions>
</x-page-header>
@if(session('status'))<div class="alert alert-success ad-flash"><i data-lucide="check-circle-2"></i><span>{{ session('status') }}</span></div>@endif
<section class="ad-kpis ad-kpis--three">
<article class="ad-kpi"><span><i data-lucide="bell"></i></span><div><small>Total Notifications</small><strong>{{ number_format($notifications->total()) }}</strong></div></article>
<article class="ad-kpi ad-kpi--violet"><span><i data-lucide="bell-ring"></i></span><div><small>Unread</small><strong>{{ number_format($unreadCount) }}</strong></div></article>
<article class="ad-kpi ad-kpi--green"><span><i data-lucide="check-check"></i></span><div><small>Read</small><strong>{{ number_format($readCount) }}</strong></div></article>
</section>
<section class="card ad-notification-card"><header class="ad-card-head"><div><span class="ad-eyebrow">Event Inbox</span><h2>Administrator alerts</h2><p>Operational and moderation events generated by enabled application rules.</p></div><span class="ad-count">{{ number_format($notifications->total()) }} records</span></header>
@forelse($notifications as $n)
<article class="ad-notification {{ !$n->read_at?'is-unread':'' }}"><span class="ad-notification__icon ad-tone-{{ $n->tone }}"><i data-lucide="{{ $n->icon }}"></i></span><div class="ad-notification__copy"><div><strong>{{ $n->title }}</strong>@if(!$n->read_at)<span class="ad-new">New</span>@endif</div>@if($n->description)<p>{{ $n->description }}</p>@endif<small>{{ $n->created_at->format('M j, Y · g:i A') }} · {{ $n->created_at->diffForHumans() }}</small></div><div class="ad-notification__actions">@if(!$n->read_at)<form action="{{ route('admin.system.notifications.mark-read',$n->id) }}" method="POST">@csrf<button class="icon-btn" title="Mark read"><i data-lucide="check"></i></button></form>@endif<form action="{{ route('admin.system.notifications.destroy',$n->id) }}" method="POST" onsubmit="return confirm('Delete this notification?')">@csrf @method('DELETE')<button class="icon-btn icon-btn--danger" title="Delete"><i data-lucide="trash-2"></i></button></form></div></article>
@empty<div class="ad-empty"><span><i data-lucide="bell-off"></i></span><h3>Notification inbox is clear</h3><p>Alerts will appear when enabled rules are triggered by real application events.</p></div>@endforelse
</section>
<div class="ad-pagination">{{ $notifications->links() }}</div>
</div>
@endsection
