@extends('layouts.admin')
@section('title','AI Models')
@section('content')
<x-page-header title="AI Models" subtitle="Manage AI models, versions, pricing and capabilities" :breadcrumb="['AI Management','AI Models']"><x-slot:actions><a href="{{ route('admin.models.create') }}" class="btn btn-primary btn-sm"><i data-lucide="plus"></i> Add Model</a></x-slot:actions></x-page-header>
@if(session('status'))<div class="alert alert-success" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
<form method="GET" class="card card-pad" style="margin-bottom:16px;display:grid;grid-template-columns:2fr repeat(4,1fr) auto auto;gap:8px;">
<input class="input" name="search" value="{{ request('search') }}" placeholder="Search models...">
<select class="select" name="company_id"><option value="">All Companies</option>@foreach($companies as $c)<option value="{{ $c->id }}" @selected((string)request('company_id')===(string)$c->id)>{{ $c->name }}</option>@endforeach</select>
<select class="select" name="tool_id"><option value="">All Tools</option>@foreach($tools as $t)<option value="{{ $t->id }}" @selected((string)request('tool_id')===(string)$t->id)>{{ $t->name }}</option>@endforeach</select>
<select class="select" name="capability"><option value="">Any Capability</option>@foreach(['Reasoning','Vision','Audio','Image','Video','API Support'] as $c)<option value="{{ $c }}" @selected(request('capability')===$c)>{{ $c }}</option>@endforeach</select>
<select class="select" name="status"><option value="">All Status</option>@foreach(['active'=>'Active','preview'=>'Preview','deprecated'=>'Deprecated'] as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select>
<button class="btn btn-secondary btn-sm">Filter</button><a class="btn btn-secondary btn-sm" href="{{ route('admin.models.index') }}">Reset</a></form>
<div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Model</th><th>Company</th><th>Tool</th><th>Version</th><th>Context</th><th>Input/1M</th><th>Output/1M</th><th>Score</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($models as $model)<tr><td><a href="{{ route('admin.models.show',$model->id) }}"><b>{{ $model->name }}</b></a></td><td>{{ $model->company?->name ?? '—' }}</td><td>{{ $model->tool?->name ?? '—' }}</td><td>{{ $model->version ?: '—' }}</td><td>{{ $model->context_window ?: '—' }}</td><td class="mono">{{ $model->input_price_per_million!==null ? '$'.number_format($model->input_price_per_million,2) : '—' }}</td><td class="mono">{{ $model->output_price_per_million!==null ? '$'.number_format($model->output_price_per_million,2) : '—' }}</td><td class="mono">{{ number_format((float)$model->benchmark_score,1) }}</td><td><x-status-badge status="{{ ucfirst($model->status) }}" type="{{ $model->status==='active'?'pos':($model->status==='preview'?'warn':'neutral') }}" /></td><td><div class="flex gap-8"><a class="icon-btn" href="{{ route('admin.models.edit',$model->id) }}"><i data-lucide="pencil"></i></a><form method="POST" action="{{ route('admin.models.destroy',$model->id) }}" onsubmit="return confirm('Delete this model?')">@csrf @method('DELETE')<button class="icon-btn"><i data-lucide="trash-2"></i></button></form></div></td></tr>@empty<tr><td colspan="10" style="text-align:center;padding:32px;">No models found.</td></tr>@endforelse
</tbody></table></div><div class="pager"><span>Showing {{ $models->firstItem() ?? 0 }}–{{ $models->lastItem() ?? 0 }} of {{ $models->total() }}</span><div class="pager-btns">{{ $models->links() }}</div></div></div>
@endsection
