@extends('layouts.admin')
@section('title',$model->name.' · AI Model')
@section('content')
<x-page-header title="{{ $model->name }}" subtitle="AI model specification and benchmark profile" :breadcrumb="['AI Management','AI Models',$model->name]"><x-slot:actions><a href="{{ route('admin.models.edit',$model->id) }}" class="btn btn-primary btn-sm"><i data-lucide="pencil"></i> Edit Model</a></x-slot:actions></x-page-header>
@if(session('status'))<div class="alert alert-success" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
<div class="kpi-grid" style="grid-template-columns:repeat(4,1fr);margin-bottom:16px;"><x-kpi-card icon="gauge" label="Benchmark" value="{{ number_format((float)$model->benchmark_score,1) }}"/><x-kpi-card icon="box" label="Context" value="{{ $model->context_window ?: '—' }}"/><x-kpi-card icon="calendar" label="Release" value="{{ $model->release_date?->format('M Y') ?? '—' }}"/><x-kpi-card icon="activity" label="Status" value="{{ ucfirst($model->status) }}"/></div>
<div class="grid-12"><div class="col-8"><div class="card card-pad" style="margin-bottom:16px;"><h3 style="margin-top:0;">Capabilities</h3><div class="flex gap-8" style="flex-wrap:wrap;">@forelse($model->capabilities ?? [] as $c)<span class="badge badge-violet">{{ $c }}</span>@empty<span class="text-sub">No capabilities recorded.</span>@endforelse</div>@if($model->capability_notes)<p style="margin-top:16px;">{{ $model->capability_notes }}</p>@endif</div>
<div class="card card-pad"><h3 style="margin-top:0;">Benchmark Breakdown</h3>@forelse($model->benchmarks ?? [] as $name=>$score)<div class="flex" style="justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--border-soft);"><span>{{ is_string($name)?$name:'Benchmark' }}</span><b>{{ is_array($score)?json_encode($score):$score }}</b></div>@empty<span class="text-sub">No per-benchmark results recorded yet.</span>@endforelse</div></div>
<div class="col-4"><div class="card card-pad"><h3 style="margin-top:0;">Model Data</h3><p><b>Company:</b> {{ $model->company?->name ?? '—' }}</p><p><b>Tool:</b> {{ $model->tool?->name ?? '—' }}</p><p><b>Version:</b> {{ $model->version ?: '—' }}</p><p><b>Input:</b> {{ $model->input_price_per_million!==null ? '$'.number_format($model->input_price_per_million,2).'/1M' : '—' }}</p><p><b>Output:</b> {{ $model->output_price_per_million!==null ? '$'.number_format($model->output_price_per_million,2).'/1M' : '—' }}</p><p><b>Slug:</b> <span class="mono">{{ $model->slug }}</span></p></div></div></div>
@endsection
