@extends('frontend.layouts.app')
@section('title', 'Cookie Policy — AI Orbit')
@section('meta_description', 'Learn how AI Orbit may use essential, preference and analytics cookies or similar browser storage.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/institutional.css') }}">@endpush
@section('content')
<section class="inst-hero inst-hero-compact"><div class="inst-wrap"><span class="inst-eyebrow"><i data-lucide="cookie"></i> Legal</span><h1>Cookie <span>Policy</span></h1><p>A clear explanation of browser storage that may be used to keep AI Orbit secure, remember preferences and understand product usage.</p></div></section>
<div class="inst-wrap inst-stack">
<section class="inst-section"><div class="inst-section-head"><span>Overview</span><h2>What cookies and similar technologies do.</h2><p>Cookies are small values stored by a browser. Similar technologies can include local storage or session storage. The exact technologies in use can change as the product evolves.</p></div><div class="inst-value-grid"><article class="inst-value"><i data-lucide="lock-keyhole"></i><h3>Essential</h3><p>Used for sessions, security, CSRF protection, authentication and features that cannot work reliably without browser state.</p></article><article class="inst-value"><i data-lucide="sliders-horizontal"></i><h3>Preferences</h3><p>May remember interface settings such as theme, language or other choices.</p></article><article class="inst-value"><i data-lucide="chart-no-axes-combined"></i><h3>Analytics</h3><p>May help measure usage, page performance and feature adoption when analytics are enabled.</p></article><article class="inst-value"><i data-lucide="shield-check"></i><h3>Security</h3><p>May support abuse prevention, rate limiting and account protection.</p></article></div></section>
<section class="inst-split"><div class="inst-panel"><span class="inst-mini-title">Control</span><h2>Your browser gives you choices.</h2><div class="inst-check-list"><div><i data-lucide="check"></i><span>You can clear stored cookies from your browser settings.</span></div><div><i data-lucide="check"></i><span>You can block some or all cookies, though essential site functions may stop working.</span></div><div><i data-lucide="check"></i><span>Privacy tools or browser settings may also limit analytics and third-party technologies.</span></div></div></div><div class="inst-panel"><span class="inst-mini-title">Third parties</span><h2>External services</h2><p style="color:#8f9bbb;line-height:1.7">Pages may load third-party resources such as fonts, icons, analytics, media or provider links. Those services may have their own privacy and cookie practices. AI Orbit's own policy does not control third-party websites you choose to visit.</p></div></section>
<section class="inst-callout"><div><span class="inst-eyebrow"><i data-lucide="circle-help"></i> Questions</span><h2>Need clarification about browser data?</h2><p>Use the contact page and select a general or technical topic.</p></div><a class="inst-btn primary" href="{{ route('contact') }}">Contact AI Orbit</a></section>
</div>
@endsection
