@extends('frontend.layouts.app')
@section('title', 'Corrections Policy — AI Orbit')
@section('meta_description', 'Learn how to report factual, pricing, benchmark, news and editorial errors to AI Orbit and how corrections are reviewed.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/institutional.css') }}">@endpush
@section('content')
<section class="inst-hero inst-hero-compact"><div class="inst-wrap"><span class="inst-eyebrow"><i data-lucide="file-pen-line"></i> Corrections policy</span><h1>How AI Orbit handles <span>errors and updates.</span></h1><p>Corrections should improve the underlying record and evidence—not merely hide a problem in the interface.</p></div></section>
<div class="inst-wrap inst-method-grid">
    <aside class="inst-toc"><strong>On this page</strong><a href="#scope">What to report</a><a href="#submit">How to report</a><a href="#review">Review process</a><a href="#material">Material corrections</a><a href="#disputes">Disagreements</a><a href="#privacy">Submission privacy</a></aside>
    <div class="inst-method-content">
        <section id="scope" class="inst-method-card"><span class="inst-step">01</span><h2>What to report</h2><p>Useful correction reports include factual inaccuracies, stale pricing, incorrect product status, broken or outdated sources, benchmark attribution problems, misleading entity links, duplicated news, or editorial statements that conflict with the evidence shown on the page.</p></section>
        <section id="submit" class="inst-method-card"><span class="inst-step">02</span><h2>How to report a correction</h2><p>Include the affected AI Orbit URL, the specific statement or field you believe is wrong, and the best source available. For pricing, include the plan and billing period. For benchmark issues, identify the benchmark or test. For news, include the original source and explain the relevance problem.</p><div class="inst-actions"><a class="inst-btn primary" href="{{ route('contact', ['topic' => 'data_correction', 'subject' => 'Data correction']) }}">Report a correction <i data-lucide="arrow-right"></i></a><a class="inst-btn" href="{{ route('submissions.create') }}">Structured data submission</a></div></section>
        <section id="review" class="inst-method-card"><span class="inst-step">03</span><h2>Review process</h2><div class="inst-flow"><div><i data-lucide="inbox"></i><b>Receive</b><span>Correction or evidence arrives</span></div><i data-lucide="arrow-right"></i><div><i data-lucide="scan-search"></i><b>Verify</b><span>Check the affected record and source</span></div><i data-lucide="arrow-right"></i><div><i data-lucide="database-zap"></i><b>Update</b><span>Correct structured data or editorial content</span></div><i data-lucide="arrow-right"></i><div><i data-lucide="circle-check"></i><b>Publish</b><span>Refresh the public page when appropriate</span></div></div></section>
        <section id="material" class="inst-method-card"><span class="inst-step">04</span><h2>Material corrections</h2><p>A material correction is one that can change a reader's understanding or decision—for example a wrong price, provider, benchmark result, lifecycle status or factual conclusion. The preferred fix is to update the authoritative stored field or content record so related pages inherit the correction consistently.</p></section>
        <section id="disputes" class="inst-method-card"><span class="inst-step">05</span><h2>Disagreements & interpretation</h2><p>Not every disagreement is a factual error. Editorial judgment, benchmark interpretation and community opinion can reasonably differ. When the dispute concerns interpretation, AI Orbit should preserve the underlying evidence and clarify the basis of the conclusion rather than rewriting a measured result to match an opinion.</p></section>
        <section id="privacy" class="inst-method-card inst-warning"><span class="inst-step">06</span><h2>Submission privacy</h2><p>Do not send passwords, API keys or other sensitive credentials. Contact and correction submissions are handled under the Privacy Policy and may be retained for moderation, clarification and abuse prevention.</p><div class="inst-actions"><a class="inst-btn" href="{{ route('privacy') }}">Privacy Policy</a><a class="inst-btn" href="{{ route('sourcing-verification') }}">Sourcing & Verification</a></div></section>
    </div>
</div>
@endsection
