@extends('frontend.layouts.app')
@section('title', 'Disclosures & Independence — AI Orbit')
@section('meta_description', 'Read AI Orbit disclosures covering editorial independence, provider claims, affiliate relationships, ratings and third-party trademarks.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/institutional.css') }}">@endpush
@section('content')
<section class="inst-hero inst-hero-compact"><div class="inst-orb inst-orb-a"></div><div class="inst-wrap"><span class="inst-eyebrow"><i data-lucide="badge-info"></i> Transparency</span><h1>Disclosures & <span>Independence</span></h1><p>How AI Orbit separates provider claims, editorial judgment, measured results and commercial relationships.</p></div></section>
<div class="inst-wrap inst-stack">
<section class="inst-section"><div class="inst-section-head"><span>Editorial separation</span><h2>Research signals should remain distinguishable.</h2><p>Provider-supplied facts, community reviews, editorial summaries, benchmark results and AI-generated processing should not be presented as if they are the same kind of evidence.</p></div><div class="inst-value-grid"><article class="inst-value"><i data-lucide="building-2"></i><h3>Provider claims</h3><p>Specifications and pricing may originate from official product pages or source records and can change without notice.</p></article><article class="inst-value"><i data-lucide="flask-conical"></i><h3>Measured results</h3><p>Test Lab and benchmark records should expose methodology, prompts or scoring context where stored data supports it.</p></article><article class="inst-value"><i data-lucide="message-square-text"></i><h3>Reviews</h3><p>Community and editorial reviews are opinion signals and should not be confused with laboratory measurements.</p></article><article class="inst-value"><i data-lucide="sparkles"></i><h3>AI processing</h3><p>AI-generated summaries or tags can assist organization, but important facts should remain traceable to sources and moderation workflows.</p></article></div></section>
<section class="inst-split"><div class="inst-panel"><span class="inst-mini-title">Commercial relationships</span><h2>Advertising and affiliate links</h2><p style="color:#8f9bbb;line-height:1.7">If AI Orbit introduces sponsored placements, affiliate links or paid partnerships, they should be labeled so users can distinguish commercial content from ordinary rankings and editorial analysis. Payment should not silently alter benchmark results or factual data.</p></div><div class="inst-panel"><span class="inst-mini-title">Third-party rights</span><h2>Names, logos and trademarks</h2><p style="color:#8f9bbb;line-height:1.7">Third-party product names, logos and trademarks belong to their respective owners. Their appearance on AI Orbit is for identification and research context and does not by itself imply sponsorship, endorsement or affiliation.</p></div></section>
<section class="inst-callout"><div><span class="inst-eyebrow"><i data-lucide="book-open-check"></i> Methodology</span><h2>Want the scoring details?</h2><p>Our methodology page explains ratings, benchmark normalization, Test Lab scoring, pricing intelligence and editorial controls.</p></div><a class="inst-btn primary" href="{{ route('methodology') }}">Read Methodology</a></section>
</div>
@endsection
