@extends('frontend.layouts.app')
@section('title', 'Editorial Guidelines — AI Orbit')
@section('meta_description', 'Read AI Orbit editorial standards for guides, reviews, summaries, decision briefs, AI-assisted processing, conflicts and corrections.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/institutional.css') }}">@endpush
@section('content')
<section class="inst-hero inst-hero-compact"><div class="inst-orb inst-orb-a"></div><div class="inst-wrap"><span class="inst-eyebrow"><i data-lucide="book-open-check"></i> Editorial standards</span><h1>How AI Orbit publishes <span>editorial analysis.</span></h1><p>These guidelines explain how AI Orbit separates factual records, measured results, provider claims, community opinion and editorial judgment.</p></div></section>
<div class="inst-wrap inst-method-grid">
    <aside class="inst-toc"><strong>On this page</strong><a href="#purpose">Purpose</a><a href="#evidence">Evidence & claims</a><a href="#analysis">Editorial analysis</a><a href="#automation">AI assistance</a><a href="#reviews">Review controls</a><a href="#commercial">Commercial separation</a><a href="#updates">Updates & corrections</a></aside>
    <div class="inst-method-content">
        <section id="purpose" class="inst-method-card"><span class="inst-step">01</span><h2>Purpose</h2><p>AI Orbit aims to help readers discover, compare and understand AI products without presenting every data point as equally certain. Editorial content should clarify the evidence already available, identify practical trade-offs and make uncertainty visible.</p><div class="inst-rule-grid"><div><i data-lucide="scale"></i><b>Useful, not promotional</b><span>Editorial copy should help a reader decide, not simply repeat marketing language.</span></div><div><i data-lucide="layers-3"></i><b>Signal separation</b><span>Measured results, stored facts, community opinion and editorial interpretation remain distinguishable.</span></div><div><i data-lucide="circle-help"></i><b>Unknown stays unknown</b><span>Missing product facts should not be filled with invented precision.</span></div></div></section>
        <section id="evidence" class="inst-method-card"><span class="inst-step">02</span><h2>Evidence & factual claims</h2><p>Important factual statements should be supported by a stored source, provider documentation, verified benchmark record or another traceable data record where the product supports that evidence. When evidence is incomplete, the interface may label the claim as pending or omit it.</p><div class="inst-metric-table"><div><b>Provider facts</b><span>Pricing, specifications, availability and policies can originate from official provider documentation.</span></div><div><b>Measured results</b><span>Benchmark scores should preserve test, source and verification context.</span></div><div><b>Editorial conclusions</b><span>Interpretation should be grounded in recorded evidence and clearly presented as analysis rather than measurement.</span></div><div><b>Community opinion</b><span>User ratings and reviews are subjective signals and remain separate from verified factual records.</span></div></div></section>
        <section id="analysis" class="inst-method-card"><span class="inst-step">03</span><h2>Editorial analysis & decision support</h2><p>Guides, reviews and decision briefs may summarize strengths, limitations, best-fit use cases and alternatives. These sections should prefer the site's structured evidence and published relationships over unsupported assumptions.</p><div class="inst-check-list"><div><i data-lucide="check"></i><span>Strengths should reflect recorded capabilities, verified facts, pricing evidence, benchmarks or reviewed experience.</span></div><div><i data-lucide="check"></i><span>Limitations should distinguish a known weakness from a missing data point.</span></div><div><i data-lucide="check"></i><span>Alternatives should be connected through relevant use cases, capabilities, pricing, taxonomy or comparison evidence.</span></div><div><i data-lucide="check"></i><span>“Best” or ranking language should have a defined basis rather than acting as a universal claim.</span></div></div></section>
        <section id="automation" class="inst-method-card"><span class="inst-step">04</span><h2>AI-assisted processing</h2><p>AI Orbit may use automation or AI assistance for classification, entity linking, tagging, summarization, duplicate detection, drafting support or content organization. Automated output is not treated as an independent source of truth.</p><div class="inst-rule-grid"><div><i data-lucide="sparkles"></i><b>Assist</b><span>Automation can help organize and draft information.</span></div><div><i data-lucide="shield-check"></i><b>Verify</b><span>Material factual claims should remain tied to sources or defined data records.</span></div><div><i data-lucide="user-check"></i><b>Review</b><span>Editorial publication and corrections remain controlled by the site's workflow where configured.</span></div></div></section>
        <section id="reviews" class="inst-method-card"><span class="inst-step">05</span><h2>Review and approval controls</h2><p>Articles can carry author, reviewer, approval and update information when those records exist. Community reviews are moderated before public display. A reviewer name is shown only when a reviewer is actually attached to the published record.</p></section>
        <section id="commercial" class="inst-method-card"><span class="inst-step">06</span><h2>Commercial separation</h2><p>Advertising, sponsorship or affiliate economics should not buy a verified factual claim, benchmark result or favorable editorial conclusion. Sponsored treatment should be distinguishable from ordinary editorial and research content.</p><a class="inst-inline-link" href="{{ route('disclosures') }}">Read disclosures & independence <i data-lucide="arrow-right"></i></a></section>
        <section id="updates" class="inst-method-card inst-warning"><span class="inst-step">07</span><h2>Updates, disagreements & corrections</h2><p>AI products change quickly. When a factual error is reported, AI Orbit should review the underlying record and source rather than masking the issue with presentation text. Material corrections should flow through the structured data or editorial workflow that produced the public page.</p><div class="inst-actions"><a class="inst-btn primary" href="{{ route('corrections-policy') }}">Corrections Policy</a><a class="inst-btn" href="{{ route('contact', ['topic' => 'data_correction', 'subject' => 'Data correction']) }}">Report a correction</a></div></section>
    </div>
</div>
@endsection
