@extends('frontend.layouts.app')
@section('title', 'Methodology — How AI Hub Ranks, Reviews & Verifies AI')
@section('meta_description', 'Understand how AI Hub handles tool ratings, model benchmarks, Test Lab experiments, pricing intelligence, news verification and editorial transparency.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/institutional.css') }}">@endpush
@section('content')
<section class="inst-hero inst-hero-compact"><div class="inst-wrap"><span class="inst-eyebrow"><i data-lucide="microscope"></i> Research methodology</span><h1>How AI Hub turns raw data into <span>useful intelligence.</span></h1><p>Our methodology is designed around traceability: what a metric means, where it came from, and which parts are measured, editorial or community-provided.</p></div></section>
<div class="inst-wrap inst-method-grid">
    <aside class="inst-toc"><strong>On this page</strong><a href="#principles">Core principles</a><a href="#tools">Tool ratings</a><a href="#models">Model benchmarks</a><a href="#testlab">Test Lab</a><a href="#pricing">Pricing intelligence</a><a href="#news">News verification</a><a href="#reviews">Reviews</a><a href="#editorial">Editorial policy</a><a href="#limitations">Limitations</a></aside>
    <div class="inst-method-content">
        <section id="principles" class="inst-method-card"><span class="inst-step">01</span><h2>Core principles</h2><p>AI Hub prioritizes structured, comparable data and avoids presenting unavailable fields as facts. Public pages should use published/active records, preserve source context and distinguish calculated scores from direct observations.</p><div class="inst-rule-grid"><div><i data-lucide="database"></i><b>Database first</b><span>Display values should come from stored records or defined calculations.</span></div><div><i data-lucide="shield-check"></i><b>Verification visible</b><span>Verified benchmark/news states are shown separately from unverified data.</span></div><div><i data-lucide="eye"></i><b>Transparent labels</b><span>Editorial, community and measured signals should not be blended silently.</span></div></div></section>
        <section id="tools" class="inst-method-card"><span class="inst-step">02</span><h2>AI Tool ratings & discovery</h2><p>Tool pages can use existing rating, popularity and benchmark fields alongside categories, pricing models, capabilities and reviews. These signals serve different purposes and should not be treated as interchangeable.</p><div class="inst-metric-table"><div><b>Rating</b><span>Stored product rating used for ordering and discovery where available.</span></div><div><b>Popularity</b><span>Relative discovery signal stored for a tool; it is not presented as audited market share.</span></div><div><b>Benchmark score</b><span>Performance-oriented score linked to benchmark data where available.</span></div><div><b>Reviews</b><span>Editorial/community assessments shown separately from automated or benchmark signals.</span></div></div></section>
        <section id="models" class="inst-method-card"><span class="inst-step">03</span><h2>AI Model benchmarks & leaderboards</h2><p>Leaderboards prefer verified benchmark results. Where a composite score is shown, normalized benchmark performance can be combined using the benchmark's configured weight and maximum score. This is a comparative interface metric, not a claim that one model is universally best.</p><div class="inst-formula"><span>Normalized result</span><strong>(score ÷ benchmark max score) × weight</strong><small>Composite rankings depend on available coverage. Missing benchmarks can affect comparability.</small></div></section>
        <section id="testlab" class="inst-method-card"><span class="inst-step">04</span><h2>AI Test Lab experiments</h2><p>Test Lab uses a locked shared prompt, a test-specific rubric and one or more controlled runs per model. Quick tests use one run; verified protocols can require three runs so the public result shows an average and score range instead of treating one sample as broad evidence. Automatic checks only score deterministic signals they can actually measure. Missing or irrelevant criteria are marked N/A and excluded from the weighted calculation rather than receiving a neutral filler score.</p><div class="inst-flow"><div><i data-lucide="file-lock-2"></i><b>1. Lock</b><span>Prompt + rubric</span></div><i data-lucide="arrow-right"></i><div><i data-lucide="repeat-2"></i><b>2. Run</b><span>Same protocol</span></div><i data-lucide="arrow-right"></i><div><i data-lucide="scan-search"></i><b>3. Review</b><span>Rubric + evidence</span></div><i data-lucide="arrow-right"></i><div><i data-lucide="trophy"></i><b>4. Aggregate</b><span>Average + range</span></div></div></section>
        <section id="pricing" class="inst-method-card"><span class="inst-step">05</span><h2>Pricing Intelligence</h2><p>Pricing pages separate current plans, historical snapshots, source records and detected price changes. A price shown without its billing period or plan context can be misleading, so the UI preserves those distinctions whenever the source data supports them.</p></section>
        <section id="news" class="inst-method-card"><span class="inst-step">06</span><h2>News sourcing & verification</h2><p>News intelligence can include source identity, publish time, AI summary/tags, importance, sentiment, verification state and duplicate detection. AI summaries are treated as summaries—not replacements for the original source—and source links remain important context.</p></section>
        <section id="reviews" class="inst-method-card"><span class="inst-step">07</span><h2>Reviews & community signals</h2><p>Published reviews are moderated before public display. Editorial reviews and community reviews can coexist, but their origin should remain visible. Reviews are subjective evidence and are not equivalent to controlled benchmark measurements.</p></section>
        <section id="editorial" class="inst-method-card"><span class="inst-step">08</span><h2>Editorial policy</h2><div class="inst-check-list"><div><i data-lucide="check"></i><span>Provider marketing claims should not automatically become AI Hub conclusions.</span></div><div><i data-lucide="check"></i><span>Commercial relationships should not silently determine rankings.</span></div><div><i data-lucide="check"></i><span>Corrections should update structured records rather than being hidden in presentation text.</span></div><div><i data-lucide="check"></i><span>Material uncertainty should be communicated when evidence is incomplete.</span></div></div></section>
        <section id="limitations" class="inst-method-card inst-warning"><span class="inst-step">09</span><h2>Limitations you should know</h2><p>AI products change rapidly. Pricing, model capabilities, benchmark methodology and provider policies can change after collection. Benchmarks also measure specific tasks—not every real-world workflow. AI Hub should therefore support decisions, not replace independent testing for high-stakes purchases or deployments.</p><a href="{{ route('contact') }}">Report a methodology or data concern <i data-lucide="arrow-right"></i></a></section>
    </div>
</div>
@endsection
