@extends('frontend.layouts.app')
@section('title', 'Privacy Policy — AI Orbit')
@section('meta_description', 'Read how AI Orbit handles account, contact, saved-library, analytics and technical data.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/institutional.css') }}">@endpush
@section('content')
<section class="inst-hero inst-hero-compact"><div class="inst-orb inst-orb-a"></div><div class="inst-wrap"><span class="inst-eyebrow"><i data-lucide="shield-check"></i> Legal</span><h1>Privacy <span>Policy</span></h1><p>How AI Orbit handles information when you browse, create an account, save content, submit feedback or contact us.</p></div></section>
<div class="inst-wrap inst-method-grid">
<aside class="inst-toc"><strong>On this page</strong><a href="#collect">Information we collect</a><a href="#use">How we use it</a><a href="#sharing">Sharing</a><a href="#retention">Retention</a><a href="#rights">Your choices</a><a href="#security">Security</a><a href="#contact">Contact</a></aside>
<div class="inst-method-content">
<section id="collect" class="inst-method-card"><span class="inst-step">01</span><h2>Information we collect</h2><p>Depending on how you use AI Orbit, we may process account details such as name and email, saved-library records tied to your account, contact or correction submissions, and limited technical information needed for security and abuse prevention. Contact submissions may include a one-way hash derived from an IP address rather than storing the raw address in that record.</p></section>
<section id="use" class="inst-method-card"><span class="inst-step">02</span><h2>How we use information</h2><p>We use information to operate accounts and saved items, answer messages, review corrections and submissions, protect the service, understand product performance, and improve discovery, comparison and research features.</p></section>
<section id="sharing" class="inst-method-card"><span class="inst-step">03</span><h2>When information may be shared</h2><p>We do not design AI Orbit around selling personal information. Information may be processed by infrastructure or service providers necessary to run the product, or disclosed when required by law, to protect users, or to investigate abuse or security incidents.</p></section>
<section id="retention" class="inst-method-card"><span class="inst-step">04</span><h2>Retention</h2><p>We aim to keep personal information only as long as reasonably necessary for the purpose for which it was collected, including operational, legal, security and dispute-resolution needs. Saved items generally remain until removed or the related account/data is deleted.</p></section>
<section id="rights" class="inst-method-card"><span class="inst-step">05</span><h2>Your choices</h2><p>You can remove saved items from your library and may contact us about access, correction or deletion requests concerning information associated with you. Available rights can vary by location.</p><a href="{{ route('contact') }}">Contact AI Orbit about privacy <i data-lucide="arrow-right"></i></a></section>
<section id="security" class="inst-method-card"><span class="inst-step">06</span><h2>Security</h2><p>We use reasonable technical and organizational safeguards, but no internet service can guarantee absolute security. Users should protect account credentials and avoid sending sensitive information through general feedback forms.</p></section>
<section id="contact" class="inst-method-card inst-warning"><span class="inst-step">07</span><h2>Questions or updates</h2><p>This policy may change as AI Orbit adds features or service providers. Material updates should be reflected on this page. For privacy questions, use the contact page.</p><a href="{{ route('contact') }}">Open Contact <i data-lucide="arrow-right"></i></a></section>
</div></div>
@endsection
