@extends('frontend.layouts.app')
@section('title', 'Sourcing & Verification Standards — AI Orbit')
@section('meta_description', 'Learn how AI Orbit handles official sources, pricing freshness, benchmark evidence, AI news relevance, confidence scores and verification states.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/institutional.css') }}">@endpush
@section('content')
<section class="inst-hero inst-hero-compact"><div class="inst-orb inst-orb-b"></div><div class="inst-wrap"><span class="inst-eyebrow"><i data-lucide="scan-search"></i> Sourcing & verification</span><h1>What counts as evidence on <span>AI Orbit.</span></h1><p>Verification is not one universal badge. The source, claim type, freshness and measurement context all matter.</p></div></section>
<div class="inst-wrap inst-method-grid">
    <aside class="inst-toc"><strong>On this page</strong><a href="#hierarchy">Source hierarchy</a><a href="#tools">Tools</a><a href="#pricing">Pricing</a><a href="#benchmarks">Benchmarks</a><a href="#news">News</a><a href="#confidence">Confidence scores</a><a href="#freshness">Freshness</a></aside>
    <div class="inst-method-content">
        <section id="hierarchy" class="inst-method-card"><span class="inst-step">01</span><h2>Source hierarchy</h2><p>AI Orbit prefers the most direct evidence appropriate to the claim. An official provider page is usually stronger for a current price or product policy, while an independent benchmark source may be more appropriate for a performance result.</p><div class="inst-metric-table"><div><b>Official / primary</b><span>Provider documentation, pricing pages, release notes, repositories, policy pages and first-party announcements.</span></div><div><b>Measured / research</b><span>Benchmark datasets, research papers or structured test records with identifiable methodology.</span></div><div><b>Reliable secondary</b><span>Reputable reporting or analysis used when it adds context that is not available from a primary record.</span></div><div><b>Community / opinion</b><span>Useful for experience signals, but not a substitute for source-backed factual verification.</span></div></div></section>
        <section id="tools" class="inst-method-card"><span class="inst-step">02</span><h2>Tool profile verification</h2><p>Tool pages can contain source-backed capabilities, use-case fits, lifecycle status, technical facts, privacy/security notes and pricing records. A “pending” state means the field exists or is relevant but has not met the configured verification condition. It is not automatically a negative judgment about the product.</p></section>
        <section id="pricing" class="inst-method-card"><span class="inst-step">03</span><h2>Pricing verification</h2><p>Pricing should preserve the plan, billing period, currency, unit and source context. A current price can become stale quickly, so freshness and verification dates are displayed where records support them. Custom or enterprise pricing should remain “custom” when no public numeric rate exists.</p><div class="inst-rule-grid"><div><i data-lucide="badge-dollar-sign"></i><b>Plan context</b><span>Free, monthly, annual, usage-based and custom plans should not be collapsed into one number.</span></div><div><i data-lucide="calendar-check"></i><b>Freshness</b><span>Verification dates help readers judge how recently a commercial fact was checked.</span></div><div><i data-lucide="history"></i><b>Change history</b><span>Historical snapshots can be separated from the currently stored plan state.</span></div></div></section>
        <section id="benchmarks" class="inst-method-card"><span class="inst-step">04</span><h2>Benchmark evidence</h2><p>Verified benchmark records should preserve the benchmark identity, score, source, test date and semantic class. Scores from materially different test types should not be blended as if they measured the same thing. Composite scores are comparative interface metrics, not universal product-quality claims.</p><a class="inst-inline-link" href="{{ route('methodology') }}#models">Read benchmark methodology <i data-lucide="arrow-right"></i></a></section>
        <section id="news" class="inst-method-card"><span class="inst-step">05</span><h2>News relevance & verification</h2><p>AI news ingestion can use source identity, title/body relevance, entity context, duplicate detection and editorial override controls. A company or product name by itself should not make an unrelated story “AI news.” AI-generated summaries are treated as summaries and the original source remains the factual reference point.</p></section>
        <section id="confidence" class="inst-method-card"><span class="inst-step">06</span><h2>Confidence scores</h2><p>Profile confidence summarizes evidence coverage, verification and freshness for the stored record. It should not be read as a product-quality score. A low confidence score can mean incomplete evidence even when the product itself is excellent.</p><div class="inst-formula"><span>Interpretation</span><strong>Confidence = evidence coverage + verification + freshness signals</strong><small>The exact implementation can vary by record type and available fields.</small></div></section>
        <section id="freshness" class="inst-method-card inst-warning"><span class="inst-step">07</span><h2>Freshness & limitations</h2><p>AI products, prices and policies can change after verification. Dates and source links are therefore part of the evidence. If you find a newer official source or a stale record, report it so the structured data can be reviewed.</p><div class="inst-actions"><a class="inst-btn primary" href="{{ route('contact', ['topic' => 'data_correction', 'subject' => 'Source or verification update']) }}">Report stale data</a><a class="inst-btn" href="{{ route('corrections-policy') }}">Corrections Policy</a></div></section>
    </div>
</div>
@endsection
