@extends('frontend.layouts.app')
@section('title', 'Terms of Use — AI Hub')
@section('meta_description', 'Terms governing use of AI Hub, its research data, comparisons, ratings and community features.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/institutional.css') }}">@endpush
@section('content')
<section class="inst-hero inst-hero-compact"><div class="inst-orb inst-orb-b"></div><div class="inst-wrap"><span class="inst-eyebrow"><i data-lucide="file-text"></i> Legal</span><h1>Terms of <span>Use</span></h1><p>These terms describe the rules for using AI Hub and the limits of the information, ratings and comparisons presented on the platform.</p></div></section>
<div class="inst-wrap inst-method-grid"><aside class="inst-toc"><strong>Terms</strong><a href="#acceptance">Acceptance</a><a href="#research">Research information</a><a href="#accounts">Accounts</a><a href="#conduct">Acceptable use</a><a href="#content">Content & IP</a><a href="#warranty">Disclaimers</a><a href="#changes">Changes</a></aside><div class="inst-method-content">
<section id="acceptance" class="inst-method-card"><span class="inst-step">01</span><h2>Acceptance</h2><p>By using AI Hub, you agree to these terms and applicable laws. If you do not agree, do not use the service.</p></section>
<section id="research" class="inst-method-card"><span class="inst-step">02</span><h2>AI research information is not a guarantee</h2><p>Tool listings, model specifications, pricing, benchmarks, ratings, news summaries and comparisons are provided for discovery and research. AI products change quickly and information can become incomplete or outdated. Verify critical decisions with the original provider or source.</p></section>
<section id="accounts" class="inst-method-card"><span class="inst-step">03</span><h2>Accounts</h2><p>You are responsible for maintaining the confidentiality of your credentials and for activity performed through your account. Do not create accounts through deceptive or abusive methods or attempt to access another user's account.</p></section>
<section id="conduct" class="inst-method-card"><span class="inst-step">04</span><h2>Acceptable use</h2><p>Do not interfere with the service, bypass access controls, overload endpoints, submit malicious content, scrape in a way that harms availability, impersonate others, or use community features for spam, fraud or unlawful activity.</p></section>
<section id="content" class="inst-method-card"><span class="inst-step">05</span><h2>Content and intellectual property</h2><p>AI Hub's interface, original editorial material, organization and platform code may be protected by intellectual-property laws. Third-party product names, logos, screenshots and source material remain the property of their respective owners. References do not imply endorsement or affiliation.</p></section>
<section id="warranty" class="inst-method-card inst-warning"><span class="inst-step">06</span><h2>No warranty or professional advice</h2><p>AI Hub is provided on an “as available” basis. Content is not legal, financial, investment, medical or other professional advice. To the extent permitted by law, AI Hub does not guarantee uninterrupted availability, error-free data or fitness of third-party AI products for a particular purpose.</p></section>
<section id="changes" class="inst-method-card"><span class="inst-step">07</span><h2>Changes and contact</h2><p>Features and these terms may be updated over time. Continued use after an update may mean the revised terms apply. Questions can be sent through the contact page.</p><a href="{{ route('contact') }}">Contact AI Hub <i data-lucide="arrow-right"></i></a></section>
</div></div>
@endsection
