@extends('frontend.layouts.app')
@section('title', $company->name.' — AI Tools, Models & News | AI Hub')
@section('meta_description', \Illuminate\Support\Str::limit($company->description ?: 'Explore '.$company->name.' AI tools, models and latest company intelligence.', 155, ''))
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/companies.css') }}">@endpush
@section('content')
@php $logo=$company->logo_path && file_exists(public_path($company->logo_path)) ? asset($company->logo_path) : asset('favicon.ico'); @endphp
<section class="company-profile-hero"><div class="company-wrap"><div class="company-breadcrumb"><a href="{{ route('home') }}">Home</a><i data-lucide="chevron-right"></i><a href="{{ route('companies.index') }}">Companies</a><i data-lucide="chevron-right"></i><span>{{ $company->name }}</span></div><div class="company-profile-main"><div class="company-profile-id"><img src="{{ $logo }}" alt="{{ $company->name }} logo"><div><div class="company-profile-badges"><span class="company-status status-{{ $company->status }}">{{ ucfirst($company->status) }}</span>@if($company->founded_year)<span>Founded {{ $company->founded_year }}</span>@endif</div><h1>{{ $company->name }}</h1><p>{{ \Illuminate\Support\Str::limit($company->description ?: 'AI company developing products, models and developer services.', 180) }}</p></div></div><div class="company-profile-actions"><button type="button" class="save-item-btn detail-save" data-save-item data-save-type="company" data-save-id="{{ $company->id }}" aria-pressed="false"><i data-lucide="bookmark"></i><span data-save-label data-default-label="Save">Save</span></button>@if($company->website)<a class="primary" href="{{ $company->website }}" target="_blank" rel="noopener">Visit website <i data-lucide="external-link"></i></a>@endif<a href="{{ route('comparisons.builder') }}">Compare products <i data-lucide="scale"></i></a></div></div><div class="company-profile-metrics"><div><span>AI tools</span><strong>{{ number_format($company->published_tools_count) }}</strong><small>Published products</small></div><div><span>AI models</span><strong>{{ number_format($company->active_models_count) }}</strong><small>Active & preview</small></div><div><span>News signals</span><strong>{{ number_format($company->published_news_count) }}</strong><small>Published intelligence</small></div><div><span>Founded</span><strong>{{ $company->founded_year ?: '—' }}</strong><small>{{ ucfirst($company->status) }} company</small></div></div></div></section>
<nav class="company-profile-nav"><div class="company-wrap"><a href="#overview">Overview</a><a href="#tools">AI Tools</a><a href="#models">AI Models</a><a href="#news">Latest News</a></div></nav>
<section class="company-profile-body"><div class="company-wrap"><div class="company-profile-layout"><main>
<section class="company-block" id="overview"><span class="company-kicker">COMPANY OVERVIEW</span><h2>About {{ $company->name }}</h2><p class="company-lead">{{ $company->description ?: $company->name.' develops AI products, models and developer services.' }}</p><div class="company-facts"><div><span>Status</span><strong>{{ ucfirst($company->status) }}</strong></div><div><span>Founded</span><strong>{{ $company->founded_year ?: 'Not listed' }}</strong></div><div><span>Website</span><strong>{{ $company->website ? parse_url($company->website, PHP_URL_HOST) : 'Not listed' }}</strong></div><div><span>AI Hub coverage</span><strong>{{ $company->published_tools_count + $company->active_models_count }} products & models</strong></div></div></section>
<section class="company-block" id="tools"><div class="company-block-head"><div><span class="company-kicker">PRODUCT PORTFOLIO</span><h2>AI Tools</h2></div><a href="{{ route('tools.index',['q'=>$company->name]) }}">Browse tools <i data-lucide="arrow-right"></i></a></div>@if($tools->count())<div class="company-tool-grid">@foreach($tools as $tool)@php $tlogo=$tool->logo_path && file_exists(public_path($tool->logo_path)) ? asset($tool->logo_path) : $logo; @endphp<a href="{{ route('tools.show',$tool) }}"><img src="{{ $tlogo }}" alt=""><div><small>{{ $tool->category?->name ?: 'AI Tool' }}</small><strong>{{ $tool->name }}</strong><span>{{ \Illuminate\Support\Str::limit($tool->short_description ?: $tool->description, 72) }}</span></div><b>{{ number_format((float)$tool->rating,1) }}★</b></a>@endforeach</div>@else<div class="company-inline-empty">No published AI tools are linked to this company yet.</div>@endif</section>
<section class="company-block" id="models"><div class="company-block-head"><div><span class="company-kicker">MODEL INTELLIGENCE</span><h2>AI Models</h2></div><a href="{{ route('models.index',['company'=>$company->slug]) }}">Browse models <i data-lucide="arrow-right"></i></a></div>@if($models->count())<div class="company-model-grid">@foreach($models as $model)@php $mlogo=$model->logo_path && file_exists(public_path($model->logo_path)) ? asset($model->logo_path) : $logo; @endphp<a href="{{ route('models.show',$model) }}"><img src="{{ $mlogo }}" alt=""><div><small>{{ strtoupper($model->status) }}</small><strong>{{ $model->name }}</strong><span>{{ $model->context_window ?: '—' }} context · {{ $model->version ?: 'Current version' }}</span></div><b>{{ number_format((float)$model->benchmark_score,1) }}</b></a>@endforeach</div>@else<div class="company-inline-empty">No active AI models are linked to this company yet.</div>@endif</section>
<section class="company-block" id="news"><div class="company-block-head"><div><span class="company-kicker">LATEST INTELLIGENCE</span><h2>Company News</h2></div><a href="{{ route('news.index',['company'=>$company->slug]) }}">All news <i data-lucide="arrow-right"></i></a></div>@if($news->count())<div class="company-news-grid">@foreach($news as $item)@php $nimg=$item->image_path && file_exists(public_path($item->image_path)) ? asset($item->image_path) : $logo; @endphp<a href="{{ route('news.show',$item) }}"><img src="{{ $nimg }}" alt=""><div><small>{{ $item->category ?: 'AI News' }} · {{ optional($item->published_at)->diffForHumans() }}</small><strong>{{ $item->headline }}</strong><span>{{ \Illuminate\Support\Str::limit($item->ai_summary ?: $item->summary, 92) }}</span></div></a>@endforeach</div>@else<div class="company-inline-empty">No published news is linked to this company yet.</div>@endif</section>
</main><aside class="company-profile-side"><div class="company-side-card"><span class="company-side-label">COMPANY PROFILE</span><img class="company-side-logo" src="{{ $logo }}" alt=""><h3>{{ $company->name }}</h3><p>{{ \Illuminate\Support\Str::limit($company->description ?: 'AI company.', 150) }}</p>@if($company->website)<a href="{{ $company->website }}" target="_blank" rel="noopener">Official website <i data-lucide="external-link"></i></a>@endif</div><div class="company-side-card"><span class="company-side-label">RELATED COMPANIES</span>@foreach($relatedCompanies as $related)@php $rlogo=$related->logo_path && file_exists(public_path($related->logo_path)) ? asset($related->logo_path) : asset('favicon.ico'); @endphp<a class="related-company" href="{{ route('companies.show',$related) }}"><img src="{{ $rlogo }}" alt=""><div><strong>{{ $related->name }}</strong><small>{{ $related->active_models_count }} models · {{ $related->published_tools_count }} tools</small></div><i data-lucide="chevron-right"></i></a>@endforeach</div></aside></div></div></section>
@endsection
