@extends('frontend.layouts.app')
@section('title', $model->name.' — AI Model Specs, Pricing & Benchmarks | AI Hub')
@section('meta_description', 'Explore '.$model->name.' by '.($model->company?->name ?? 'its provider').': capabilities, context window, API pricing and benchmark performance.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/models.css') }}">@endpush
@section('content')
<section class="model-detail-hero"><div class="model-wrap"><div class="model-breadcrumb"><a href="{{ route('home') }}">Home</a><i data-lucide="chevron-right"></i><a href="{{ route('models.index') }}">AI Models</a><i data-lucide="chevron-right"></i><span>{{ $model->name }}</span></div><div class="model-detail-main"><div class="model-detail-id"><img src="{{ asset($model->logo_path ?: ($model->company?->logo_path ?: 'storage/ai-hub/companies/openai.png')) }}" alt="{{ $model->name }}"><div><div class="detail-badges"><span class="status-pill {{ $model->status }}">{{ ucfirst($model->status) }}</span>@if($model->release_date)<span>Released {{ $model->release_date->format('M j, Y') }}</span>@endif</div><h1>{{ $model->name }}</h1><p>By <strong>{{ $model->company?->name ?? 'Independent' }}</strong>@if($model->version) · {{ $model->version }}@endif</p></div></div><div class="model-detail-actions"><a href="#benchmarks"><i data-lucide="bar-chart-3"></i> Benchmarks</a>@if($model->tool)<a class="primary" href="{{ route('tools.show',$model->tool) }}">View {{ $model->tool->name }} <i data-lucide="arrow-up-right"></i></a>@endif</div></div><div class="detail-metrics"><div><span>Overall benchmark</span><strong>{{ number_format((float)$model->benchmark_score,1) }}</strong><small>/100</small></div><div><span>Context window</span><strong>{{ $model->context_window ?: '—' }}</strong><small>tokens</small></div><div><span>Input price</span><strong>{{ $model->input_price_per_million !== null ? '$'.number_format((float)$model->input_price_per_million,2) : '—' }}</strong><small>per 1M tokens</small></div><div><span>Output price</span><strong>{{ $model->output_price_per_million !== null ? '$'.number_format((float)$model->output_price_per_million,2) : '—' }}</strong><small>per 1M tokens</small></div></div></div></section>
<nav class="model-detail-nav"><div class="model-wrap"><a href="#overview">Overview</a><a href="#capabilities">Capabilities</a><a href="#benchmarks">Benchmarks</a><a href="#pricing">Pricing</a><a href="#related">Related models</a></div></nav>
<section class="model-detail-body"><div class="model-wrap detail-layout"><main><section id="overview" class="detail-block"><span class="section-kicker">MODEL OVERVIEW</span><h2>About {{ $model->name }}</h2><p class="detail-lead">{{ $model->capability_notes ?: $model->name.' is an AI model from '.($model->company?->name ?? 'its provider').'. Use the verified specifications and benchmarks below to compare it with other models.' }}</p><div class="spec-table"><div><span>Provider</span><strong>{{ $model->company?->name ?? '—' }}</strong></div><div><span>Version</span><strong>{{ $model->version ?: '—' }}</strong></div><div><span>Release date</span><strong>{{ $model->release_date?->format('F j, Y') ?? '—' }}</strong></div><div><span>Status</span><strong>{{ ucfirst($model->status) }}</strong></div><div><span>Context window</span><strong>{{ $model->context_window ?: '—' }}</strong></div><div><span>Associated product</span><strong>{{ $model->tool?->name ?? '—' }}</strong></div></div></section>
<section id="capabilities" class="detail-block"><span class="section-kicker">WHAT IT CAN DO</span><h2>Capabilities</h2><div class="capability-grid">@forelse($capabilities as $cap)<div><i data-lucide="sparkles"></i><strong>{{ $cap }}</strong><span>Supported model capability</span></div>@empty<div class="inline-empty">Capability data has not been added yet.</div>@endforelse</div></section>
<section id="benchmarks" class="detail-block"><span class="section-kicker">PERFORMANCE</span><h2>Benchmark profile</h2><p class="block-intro">Benchmark results help compare model performance, but scores should always be interpreted alongside methodology and test date.</p><div class="benchmark-list">@forelse($model->benchmarkResults as $result)<div><span><strong>{{ $result->benchmark?->name ?? 'Benchmark' }}</strong><small>{{ $result->source_name ?: 'Verified result' }}{{ $result->tested_at ? ' · '.$result->tested_at->format('M Y') : '' }}</small></span><div><i style="width:{{ min(100,(float)$result->score) }}%"></i></div><b>{{ number_format((float)$result->score,1) }}</b></div>@empty @foreach($benchmarks as $bench)<div><span><strong>{{ $bench['name'] }}</strong><small>Model benchmark breakdown</small></span><div><i style="width:{{ min(100,$bench['score']) }}%"></i></div><b>{{ number_format((float)$bench['score'],1) }}</b></div>@endforeach @if($benchmarks->isEmpty())<div class="inline-empty">No benchmark breakdown is available yet.</div>@endif @endforelse</div></section>
<section id="pricing" class="detail-block"><span class="section-kicker">API ECONOMICS</span><h2>Token pricing</h2><div class="pricing-pair"><div><i data-lucide="arrow-down-to-line"></i><span>Input tokens<small>Per 1 million tokens</small></span><strong>{{ $model->input_price_per_million !== null ? '$'.number_format((float)$model->input_price_per_million,2) : 'Not listed' }}</strong></div><div><i data-lucide="arrow-up-from-line"></i><span>Output tokens<small>Per 1 million tokens</small></span><strong>{{ $model->output_price_per_million !== null ? '$'.number_format((float)$model->output_price_per_million,2) : 'Not listed' }}</strong></div></div><p class="pricing-note"><i data-lucide="info"></i>Pricing can change. Production data should be checked against the provider’s official pricing source.</p></section>
<section id="related" class="detail-block"><div class="block-title-row"><div><span class="section-kicker">KEEP EXPLORING</span><h2>Related AI models</h2></div><a href="{{ route('models.index') }}">View all models <i data-lucide="arrow-right"></i></a></div><div class="related-models">@foreach($relatedModels as $related)<a href="{{ route('models.show',$related) }}"><img src="{{ asset($related->logo_path ?: ($related->company?->logo_path ?: 'storage/ai-hub/companies/openai.png')) }}" alt=""><span><strong>{{ $related->name }}</strong><small>{{ $related->company?->name }} · {{ $related->context_window ?: 'Context N/A' }}</small></span><b>{{ number_format((float)$related->benchmark_score,1) }}</b></a>@endforeach</div></section></main>
<aside class="model-detail-side"><div class="side-card provider-card"><span class="side-label">PROVIDER</span>@if($model->company?->logo_path)<img src="{{ asset($model->company->logo_path) }}" alt="">@endif<h3>{{ $model->company?->name ?? 'Independent' }}</h3><p>{{ Str::limit($model->company?->description,130) ?: 'Provider information will appear here when available.' }}</p>@if($model->company?->website)<a href="{{ $model->company->website }}" target="_blank" rel="noopener">Official website <i data-lucide="external-link"></i></a>@endif</div>
@if($model->tool)<div class="side-card product-card"><span class="side-label">AVAILABLE IN</span><div><img src="{{ asset($model->tool->logo_path ?: 'storage/ai-hub/tools/logos/chatgpt.png') }}" alt=""><span><strong>{{ $model->tool->name }}</strong><small>{{ $model->tool->short_description }}</small></span></div><a href="{{ route('tools.show',$model->tool) }}">Explore product <i data-lucide="arrow-right"></i></a></div>@endif
<div class="side-card"><span class="side-label">LATEST PROVIDER NEWS</span><div class="side-news">@forelse($latestNews as $news)<article>@if($news->image_path)<img src="{{ asset($news->image_path) }}" alt="">@endif<div><strong>{{ Str::limit($news->headline,68) }}</strong><small>{{ $news->published_at?->diffForHumans() }}</small></div></article>@empty<p class="side-empty">No related published news yet.</p>@endforelse</div></div></aside></div></section>
@endsection
