@extends('layouts.admin')
@section('title','Discovery Review')
@push('styles')<link rel="stylesheet" href="{{ asset('css/pages/discovery.css') }}">@endpush
@section('content')
<x-page-header title="Discovery Review" subtitle="Verify the evidence before creating or updating catalog data." :breadcrumb="['AI Intelligence','AI Discovery',$discovery->candidate_name]">
<x-slot:actions><a class="btn btn-secondary btn-sm" href="{{ route('admin.discovery.index') }}"><i data-lucide="arrow-left"></i>Back to Discovery</a></x-slot:actions></x-page-header>
@if(session('status'))<div class="alert alert-success discovery-alert">{{ session('status') }}</div>@endif
<div class="discovery-review-grid"><main class="card discovery-review-main"><div class="discovery-review-hero"><div class="discovery-type-icon is-{{ str_contains($discovery->entity_type,'model')?'model':'tool' }}"><i data-lucide="{{ str_contains($discovery->entity_type,'model')?'brain-circuit':'wrench' }}"></i></div><div><span class="discovery-kind">{{ strtoupper(str_replace('_',' ',$discovery->entity_type)) }}</span><h1>{{ $discovery->candidate_name }}</h1><p>{{ $discovery->headline }}</p></div><span class="discovery-confidence {{ $discovery->confidence>=85?'is-high':'is-mid' }}">{{ $discovery->confidence }}%</span></div>
<div class="discovery-evidence"><h3>RSS evidence</h3><p>{{ $discovery->summary ?: 'No RSS summary was supplied.' }}</p>@if($discovery->source_url)<a href="{{ $discovery->source_url }}" target="_blank" rel="noopener" class="btn btn-secondary btn-sm"><i data-lucide="external-link"></i>Open original source</a>@endif</div>
<div class="discovery-signals"><h3>Detection signals</h3><div>@foreach(($discovery->signals??[]) as $key=>$value)<span><b>{{ str_replace('_',' ',ucfirst($key)) }}</b>{{ is_array($value)?implode(', ',$value):($value===true?'Yes':$value) }}</span>@endforeach</div></div></main>
<aside class="card discovery-review-side"><h3>Resolution</h3><dl><div><dt>Status</dt><dd>{{ ucfirst($discovery->status) }}</dd></div><div><dt>Company</dt><dd>{{ $discovery->company?->name ?? 'Not matched' }}</dd></div><div><dt>RSS source</dt><dd>{{ $discovery->newsSource?->name ?? 'Unknown' }}</dd></div><div><dt>Detected</dt><dd>{{ $discovery->created_at->format('M d, Y H:i') }}</dd></div></dl>
@if($discovery->status==='pending')<div class="discovery-review-actions">@if(str_contains($discovery->entity_type,'model'))<form method="POST" action="{{ route('admin.discovery.model',$discovery->id) }}">@csrf<button class="btn btn-primary"><i data-lucide="brain-circuit"></i>{{ $discovery->matched_model_id?'Open Existing Model':'Create Model Draft' }}</button></form>@else<form method="POST" action="{{ route('admin.discovery.tool',$discovery->id) }}">@csrf<button class="btn btn-primary"><i data-lucide="wrench"></i>{{ $discovery->matched_tool_id?'Open Existing Tool':'Create Tool Draft' }}</button></form>@endif @if(str_contains($discovery->entity_type,'update'))<form method="POST" action="{{ route('admin.discovery.merge',$discovery->id) }}">@csrf<button class="btn btn-secondary"><i data-lucide="git-merge"></i>Mark Update Reviewed</button></form>@endif<form method="POST" action="{{ route('admin.discovery.ignore',$discovery->id) }}">@csrf<button class="btn btn-ghost"><i data-lucide="eye-off"></i>Ignore Candidate</button></form></div>@endif</aside></div>
@endsection
