@extends('layouts.admin')
@section('title',$company->name.' · Company')
@section('content')
<x-page-header title="{{ $company->name }}" subtitle="Company profile and connected AI assets" :breadcrumb="['AI Management','AI Companies',$company->name]"><x-slot:actions><a href="{{ route('admin.companies.edit',$company->id) }}" class="btn btn-primary btn-sm"><i data-lucide="pencil"></i> Edit Company</a></x-slot:actions></x-page-header>
@if(session('status'))<div class="alert alert-success" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
<div class="kpi-grid" style="grid-template-columns:repeat(4,1fr);margin-bottom:16px;"><x-kpi-card icon="wrench" label="AI Tools" value="{{ $company->tools_count }}"/><x-kpi-card icon="brain" label="AI Models" value="{{ $company->models_count }}"/><x-kpi-card icon="calendar" label="Founded" value="{{ $company->founded_year ?: '—' }}"/><x-kpi-card icon="activity" label="Status" value="{{ ucfirst($company->status) }}"/></div>
<div class="tabs"><a class="tab is-active" href="#overview">Overview</a><a class="tab" href="#tools">AI Tools</a><a class="tab" href="#models">Models</a></div>
<div id="overview" class="card card-pad" style="margin-bottom:16px;"><h3 style="margin-top:0;">Overview</h3><p>{{ $company->description ?: 'No company description yet.' }}</p>@if($company->website)<a href="{{ $company->website }}" target="_blank" rel="noopener" class="btn btn-secondary btn-sm">Visit Website <i data-lucide="external-link"></i></a>@endif</div>
<div id="tools" class="card" style="margin-bottom:16px;"><div class="card-pad"><b>AI Tools</b></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Status</th><th>Rating</th><th></th></tr></thead><tbody>@forelse($company->tools as $tool)<tr><td>{{ $tool->name }}</td><td>{{ ucfirst($tool->status) }}</td><td>{{ number_format((float)$tool->rating,1) }}</td><td><a href="{{ route('admin.tools.show',$tool->id) }}">View</a></td></tr>@empty<tr><td colspan="4" style="text-align:center;padding:24px;">No tools linked.</td></tr>@endforelse</tbody></table></div></div>
<div id="models" class="card"><div class="card-pad"><b>AI Models</b></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Version</th><th>Status</th><th></th></tr></thead><tbody>@forelse($company->models as $model)<tr><td>{{ $model->name }}</td><td>{{ $model->version ?: '—' }}</td><td>{{ ucfirst($model->status) }}</td><td><a href="{{ route('admin.models.show',$model->id) }}">View</a></td></tr>@empty<tr><td colspan="4" style="text-align:center;padding:24px;">No models linked.</td></tr>@endforelse</tbody></table></div></div>
@endsection
