@extends('frontend.layouts.app')
@section('title','AI Test Lab — Independent Model Tests | AI Hub')
@section('meta_description','Compare AI models on the same prompts with transparent criteria, measured scores and side-by-side results.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/testlab.css') }}">@endpush
@section('content')
<section class="lab-hero"><div class="lab-wrap"><div class="lab-hero-grid"><div><span class="lab-eyebrow"><i data-lucide="flask-conical"></i> INDEPENDENT AI TESTING</span><h1>Same prompt. Different models. <span>Measured results.</span></h1><p>Explore repeatable AI model tests with transparent prompts, scoring criteria and side-by-side outputs.</p><form class="lab-search" method="GET"><i data-lucide="search"></i><input name="q" value="{{ request('q') }}" placeholder="Search tests, prompts, criteria..."><button>Search tests</button></form></div><div class="lab-hero-panel"><div class="lab-signal"><span>LIVE LAB INDEX</span><b>{{ number_format($stats['results']) }}</b><small>measured model results</small></div><div class="lab-mini-stats"><div><b>{{ $stats['tests'] }}</b><span>Tests</span></div><div><b>{{ $stats['models'] }}</b><span>Models</span></div><div><b>{{ $stats['categories'] }}</b><span>Categories</span></div></div></div></div></div></section>
<section class="lab-directory"><div class="lab-wrap"><div class="lab-toolbar"><div><span>RESEARCH LIBRARY</span><h2>AI Test Lab</h2><p>{{ number_format($tests->total()) }} controlled experiments</p></div><div class="lab-actions"><button type="button" data-lab-filter-open><i data-lucide="sliders-horizontal"></i> Filters</button><form method="GET">@foreach(request()->except('sort','page') as $k=>$v)<input type="hidden" name="{{ $k }}" value="{{ $v }}">@endforeach<select name="sort" onchange="this.form.submit()"><option value="newest">Newest</option><option value="score" @selected(request('sort')==='score')>Top score</option><option value="models" @selected(request('sort')==='models')>Most models</option><option value="name" @selected(request('sort')==='name')>Name A–Z</option></select></form></div></div>
<div class="lab-layout"><div class="lab-overlay" data-lab-overlay></div><aside class="lab-filters" data-lab-filters><div class="lab-filter-mobile"><b>Filter tests</b><button data-lab-filter-close><i data-lucide="x"></i></button></div><form method="GET">@if(request('q'))<input type="hidden" name="q" value="{{ request('q') }}">@endif<div class="lab-filter-head"><b><i data-lucide="filter"></i> Filters</b><a href="{{ route('testlab.index') }}">Reset</a></div><div class="lab-filter-group"><h3>Test category</h3><label><span><input type="radio" name="category" value="" @checked(!request('category'))>All tests</span><b>{{ $stats['tests'] }}</b></label>@foreach($categories as $cat=>$count)<label><span><input type="radio" name="category" value="{{ $cat }}" @checked(request('category')===$cat)>{{ $cat }}</span><b>{{ $count }}</b></label>@endforeach</div><button class="lab-apply">Apply filters</button></form><div class="lab-method-card"><i data-lucide="shield-check"></i><h3>Transparent scoring</h3><p>Quality, accuracy, prompt adherence, creativity and speed are scored separately before the overall result is calculated.</p></div></aside>
<div class="lab-results">@forelse($tests as $test)@php($ranked=$test->results->sortByDesc('overall_score')->values())<article class="lab-test-card"><div class="lab-card-top"><div><span class="lab-category">{{ $test->category ?: 'General' }}</span><span class="lab-id">TEST #{{ str_pad($test->id,3,'0',STR_PAD_LEFT) }}</span></div><span class="lab-model-count"><i data-lucide="layers-3"></i>{{ $test->results_count }} models</span></div><h3><a href="{{ route('testlab.show',$test) }}">{{ $test->name }}</a></h3><p class="lab-prompt"><i data-lucide="terminal-square"></i>{{ \Illuminate\Support\Str::limit($test->prompt,125) }}</p><div class="lab-podium">@foreach($ranked->take(3) as $i=>$result)<div><span>#{{ $i+1 }}</span><b>{{ $result->model?->name ?? 'Model' }}</b><strong>{{ number_format((float)$result->overall_score,1) }}</strong></div>@endforeach</div><div class="lab-card-foot"><span><i data-lucide="calendar-days"></i>{{ $test->created_at->format('M j, Y') }}</span><a href="{{ route('testlab.show',$test) }}">View experiment <i data-lucide="arrow-right"></i></a></div></article>@empty<div class="lab-empty"><i data-lucide="flask-conical-off"></i><h3>No tests found</h3><p>Try clearing your search or category filter.</p></div>@endforelse
@if($tests->hasPages())<div class="lab-pagination"><a class="{{ $tests->onFirstPage()?'disabled':'' }}" href="{{ $tests->previousPageUrl() ?: '#' }}"><i data-lucide="chevron-left"></i> Previous</a><div>@foreach(range(1,$tests->lastPage()) as $p)<a class="{{ $tests->currentPage()===$p?'active':'' }}" href="{{ $tests->url($p) }}">{{ $p }}</a>@endforeach</div><a class="{{ !$tests->hasMorePages()?'disabled':'' }}" href="{{ $tests->nextPageUrl() ?: '#' }}">Next <i data-lucide="chevron-right"></i></a></div>@endif</div>
<aside class="lab-side"><div class="lab-side-card"><span class="side-kicker">MODEL LEADERBOARD</span><h3>Best in the lab</h3>@forelse($leaderboard as $i=>$model)<a href="{{ route('models.show',$model) }}"><span class="lab-rank">{{ $i+1 }}</span><span class="lab-model-logo"><img src="{{ $model->logo_url }}" alt="{{ $model->name }} logo"></span><span class="lab-model-name"><b>{{ $model->name }}</b><small>{{ $model->test_results_count }} tests</small></span><strong>{{ number_format((float)$model->lab_average,1) }}</strong></a>@empty<p>No scored results yet.</p>@endforelse</div><div class="lab-side-card"><span class="side-kicker">HOW IT WORKS</span><div class="lab-step"><b>01</b><p><strong>One prompt</strong><span>Identical task for every model.</span></p></div><div class="lab-step"><b>02</b><p><strong>Five criteria</strong><span>Each dimension scored 0–100.</span></p></div><div class="lab-step"><b>03</b><p><strong>Rank results</strong><span>Overall score is calculated automatically.</span></p></div></div></aside></div></div></section>
@endsection
@push('scripts')<script src="{{ asset('js/frontend/testlab.js') }}"></script>@endpush
