@extends('frontend.layouts.app')
@section('title','AI Test Lab Model Leaderboard | AI Hub')
@section('meta_description','Rank AI models by average performance across published AI Hub Test Lab experiments, with test coverage and verification counts visible.')
@push('head')<link rel="canonical" href="{{ route('testlab.leaderboard') }}"><meta name="robots" content="{{ request()->query() ? 'noindex,follow' : 'index,follow,max-image-preview:large' }}">@endpush
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/testlab.css') }}">@endpush
@section('content')
<section class="lab-leader-hero"><div class="lab-wrap"><a class="lab-back" href="{{ route('testlab.index') }}"><i data-lucide="arrow-left"></i>AI Test Lab</a><span class="lab-eyebrow"><i data-lucide="trophy"></i> TEST LAB LEADERBOARD</span><h1>Model performance across <span>controlled experiments.</span></h1><p>Average scores are shown together with test coverage and verification counts so one isolated result does not look like broad evidence.</p></div></section>
<section class="lab-leader-page"><div class="lab-wrap"><form class="lab-leader-filters" method="GET"><select name="category"><option value="">All test categories</option>@foreach($categories as $cat=>$count)<option value="{{ $cat }}" @selected($category===$cat)>{{ $cat }} ({{ $count }})</option>@endforeach</select><label><input type="checkbox" name="verified" value="1" @checked($verifiedOnly)> Verified results only</label><button>Apply</button>@if(request()->query())<a href="{{ route('testlab.leaderboard') }}">Reset</a>@endif</form>
<div class="lab-leader-table-wrap"><table class="lab-leader-table"><thead><tr><th>Rank</th><th>Model</th><th>Provider</th><th>Average</th><th>Test coverage</th><th>Verified</th><th></th></tr></thead><tbody>@forelse($models as $model)<tr><td><span class="leader-place">{{ ($models->currentPage()-1)*$models->perPage()+$loop->iteration }}</span></td><td><div class="leader-model"><img src="{{ $model->logo_url }}" alt=""><b>{{ $model->name }}</b></div></td><td>{{ $model->company?->name ?: '—' }}</td><td><strong class="leader-score">{{ number_format((float)$model->lab_average,1) }}</strong><small>/100</small></td><td><b>{{ $model->lab_tests }}</b> test{{ $model->lab_tests==1?'':'s' }}</td><td>@if($model->verified_lab_tests)<span class="leader-verified"><i data-lucide="badge-check"></i>{{ $model->verified_lab_tests }}</span>@else—@endif</td><td><a href="{{ route('models.show',$model) }}">Profile <i data-lucide="arrow-right"></i></a></td></tr>@empty<tr><td colspan="7"><div class="lab-empty"><h3>No leaderboard data for this filter</h3><p>Try another category or include non-verified complete results.</p></div></td></tr>@endforelse</tbody></table></div>
@if($models->hasPages())<div class="lab-pagination">{{ $models->links() }}</div>@endif
<div class="leader-note"><i data-lucide="info"></i><p><b>How to read this ranking:</b> average Test Lab score is not a universal model quality score. Coverage matters. Open individual experiments to inspect the prompt, criteria weights, evidence and result metadata.</p></div>
</div></section>
@endsection
