@extends('frontend.layouts.app')
@section('title',$test->name.' — AI Test Lab | AI Hub')
@section('meta_description','See the prompt, scoring methodology and side-by-side AI model results for '.$test->name.'.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/testlab.css') }}">@endpush
@section('content')
<section class="lab-detail-hero"><div class="lab-wrap"><a class="lab-back" href="{{ route('testlab.index') }}"><i data-lucide="arrow-left"></i> AI Test Lab</a><div class="lab-detail-title"><div><span class="lab-eyebrow"><i data-lucide="flask-conical"></i>{{ strtoupper($test->category ?: 'GENERAL') }} EXPERIMENT</span><h1>{{ $test->name }}</h1><p>{{ $test->criteria ?: 'Measured across quality, accuracy, prompt adherence, creativity and speed.' }}</p></div>@if($winner)<div class="winner-badge"><span>LAB WINNER</span><b>{{ $winner->model?->name ?? 'Model' }}</b><strong>{{ number_format((float)$winner->overall_score,1) }}</strong><small>overall score</small></div>@endif</div></div></section>
<section class="lab-detail"><div class="lab-wrap"><div class="lab-detail-grid"><main><div class="lab-panel prompt-panel"><div class="lab-panel-head"><span><i data-lucide="terminal-square"></i> TEST PROMPT</span><small>Identical input for every model</small></div><blockquote>{{ $test->prompt }}</blockquote>@if($test->expected_output)<div class="expected"><b>Expected output</b><p>{{ $test->expected_output }}</p></div>@endif</div>
<div class="lab-section-head"><div><span>RESULTS</span><h2>Model performance</h2></div><small>{{ $results->count() }} models tested</small></div>
<div class="result-stack">@forelse($results as $i=>$result)<article class="result-card"><div class="result-head"><span class="result-position">#{{ $i+1 }}</span><div class="result-logo">@if($result->model)<img src="{{ $result->model->logo_url }}" alt="{{ $result->model->name }} logo">@else AI @endif</div><div class="result-model"><h3>{{ $result->model?->name ?? 'Unknown model' }}</h3><p>{{ $result->model?->company?->name ?? 'AI model' }}</p></div><div class="result-score"><strong>{{ number_format((float)$result->overall_score,1) }}</strong><span>/100</span></div></div><div class="score-grid">@foreach(['quality'=>'Quality','accuracy'=>'Accuracy','prompt_adherence'=>'Prompt adherence','creativity'=>'Creativity','speed'=>'Speed'] as $key=>$label)@php($val=$result->{'score_'.$key})<div class="score-cell"><div><span>{{ $label }}</span><b>{{ $val===null?'—':$val }}</b></div><div class="score-track"><i style="width:{{ (int)($val ?? 0) }}%"></i></div></div>@endforeach</div><div class="response-block"><div><b><i data-lucide="message-square-text"></i> Model response</b>@if($result->model)<a href="{{ route('models.show',$result->model) }}">Model profile <i data-lucide="arrow-up-right"></i></a>@endif</div><p>{{ $result->response_text ?: 'No response text has been recorded for this result yet.' }}</p></div></article>@empty<div class="lab-empty"><h3>No results recorded yet</h3></div>@endforelse</div></main>
<aside class="lab-detail-side"><div class="lab-side-card sticky"><span class="side-kicker">METHODOLOGY</span><h3>Scoring framework</h3><p>{{ $test->criteria ?: 'Five independent dimensions contribute to the overall score.' }}</p>@foreach(['Quality'=>'Overall usefulness and clarity','Accuracy'=>'Correctness of the response','Prompt adherence'=>'How closely instructions were followed','Creativity'=>'Originality where relevant','Speed'=>'Relative response performance'] as $name=>$desc)<div class="method-row"><i data-lucide="check-circle-2"></i><p><b>{{ $name }}</b><span>{{ $desc }}</span></p></div>@endforeach<div class="formula">Overall = average of available criteria</div></div>@if($related->count())<div class="lab-side-card"><span class="side-kicker">RELATED TESTS</span><h3>More experiments</h3>@foreach($related as $item)<a class="related-test" href="{{ route('testlab.show',$item) }}"><span>{{ $item->category ?: 'General' }}</span><b>{{ $item->name }}</b><small>{{ $item->results_count }} model results <i data-lucide="arrow-right"></i></small></a>@endforeach</div>@endif</aside></div></div></section>
@endsection
