@extends('frontend.layouts.app')
@section('title',$test->seo_title)
@section('meta_description',$test->seo_description)
@push('head')
<link rel="canonical" href="{{ route('testlab.show',$test) }}">
<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">
<meta property="og:type" content="article"><meta property="og:title" content="{{ $test->seo_title }}"><meta property="og:description" content="{{ $test->seo_description }}"><meta property="og:url" content="{{ route('testlab.show',$test) }}">
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Dataset','name'=>$test->name,'description'=>$test->seo_description,'url'=>route('testlab.show',$test),'datePublished'=>optional($test->published_at)->toIso8601String(),'dateModified'=>optional($test->updated_at)->toIso8601String(),'measurementTechnique'=>$test->runModeLabel().' with a locked shared prompt and test-specific weighted rubric','variableMeasured'=>collect($criteria)->map(fn($c)=>['@type'=>'PropertyValue','name'=>$c['label'],'description'=>$c['description'],'valueReference'=>$c['weight'].'% weight'])->values()->all(),'creator'=>['@type'=>'Organization','name'=>'AI Hub']], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
@endpush
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/testlab.css') }}">@endpush
@section('content')
<section class="lab-detail-hero"><div class="lab-wrap"><a class="lab-back" href="{{ route('testlab.index') }}"><i data-lucide="arrow-left"></i> AI Test Lab</a><div class="lab-detail-title"><div><div class="lab-detail-badges"><span>{{ strtoupper($test->testTypeLabel()) }}</span><span>{{ strtoupper($test->runModeLabel()) }} · {{ $test->required_runs }}× RUNS</span><span>{{ strtoupper($test->category ?: 'GENERAL') }}</span><span>{{ strtoupper(config('test_lab.difficulties.'.$test->difficulty, ucfirst($test->difficulty))) }}</span>@if($test->is_verified)<span class="verified"><i data-lucide="badge-check"></i> VERIFIED METHODOLOGY</span>@endif</div><h1>{{ $test->name }}</h1><p>{{ $test->short_description ?: ($test->criteria ?: 'Controlled model experiment with transparent multi-run scoring.') }}</p><div class="lab-detail-meta">@if($test->feature)<a href="{{ route('features.show',$test->feature) }}"><i data-lucide="sparkles"></i>{{ $test->feature->name }}</a>@endif @if($test->useCase)<a href="{{ route('use-cases.show',$test->useCase) }}"><i data-lucide="target"></i>{{ $test->useCase->name }}</a>@endif<span><i data-lucide="layers-3"></i>{{ $results->count() }} complete model results</span><span><i data-lucide="repeat-2"></i>{{ $results->sum('run_count') }} scored runs</span><span><i data-lucide="calendar-check"></i>{{ ($test->published_at ?: $test->created_at)->format('M j, Y') }}</span></div></div>@if($winner)<div class="winner-badge"><span>TOP AGGREGATE</span><img src="{{ $winner->model?->logo_url ?: asset('favicon.ico') }}" alt=""><b>{{ $winner->model?->name ?? 'Model' }}</b><strong>{{ number_format((float)$winner->overall_score,1) }}</strong><small>{{ $winner->run_count }} run{{ $winner->run_count===1?'':'s' }} · average /100</small>@if(in_array($winner->verification_level,['verified','high_confidence'],true))<em><i data-lucide="badge-check"></i>{{ $winner->verificationLabel() }}</em>@endif</div>@endif</div></div></section>

<section class="lab-detail"><div class="lab-wrap"><div class="lab-detail-grid"><main>
    <div class="lab-panel prompt-panel"><div class="lab-panel-head"><span><i data-lucide="lock-keyhole"></i> LOCKED SHARED TEST PROMPT</span><button type="button" data-copy-prompt><i data-lucide="copy"></i>Copy</button></div><pre data-prompt-text>{{ $test->prompt }}</pre>@if($test->expected_output)<div class="expected"><b>Expected output / answer key</b><p>{{ $test->expected_output }}</p></div>@endif</div>

    <div class="lab-section-head"><div><span>CONTROLLED EVIDENCE</span><h2>Model performance</h2><p>Rankings use model-level aggregates. A model enters the ranking only after all {{ $test->required_runs }} required run{{ $test->required_runs===1?'':'s' }} are scored.</p></div><small>{{ $results->sum('run_count') }} scored runs</small></div>
    <div class="result-stack">@forelse($results as $i=>$result)
    @php($scores=$result->scores())
    <article class="result-card">
        <div class="result-head"><span class="result-position">#{{ $i+1 }}</span><div class="result-logo"><img src="{{ $result->model?->logo_url ?: asset('favicon.ico') }}" alt=""></div><div class="result-model"><h3>{{ $result->model?->name ?? 'Unknown model' }}</h3><p>{{ $result->model?->company?->name ?? 'AI model' }}@if($result->model_version) · {{ $result->model_version }}@endif</p></div>@if(in_array($result->verification_level,['verified','high_confidence'],true))<span class="result-verified"><i data-lucide="badge-check"></i>{{ $result->verificationLabel() }}</span>@elseif($result->verification_level==='reviewed')<span class="result-reviewed"><i data-lucide="clipboard-check"></i>Reviewed</span>@endif<div class="result-score"><strong>{{ number_format((float)$result->overall_score,1) }}</strong><span>/100 avg</span></div></div>

        <div class="lab-aggregate-strip"><div><span>Runs</span><b>{{ $result->run_count }}/{{ $test->required_runs }}</b></div><div><span>Score range</span><b>{{ $result->score_min!==null ? number_format((float)$result->score_min,1).'–'.number_format((float)$result->score_max,1) : '—' }}</b></div><div><span>Variation</span><b>{{ $result->score_stddev!==null ? '±'.number_format((float)$result->score_stddev,2) : '—' }}</b></div>@if($result->avg_latency_ms!==null)<div><span>Avg latency</span><b>{{ number_format($result->avg_latency_ms) }} ms</b></div>@endif @if($result->avg_estimated_cost_usd!==null)<div><span>Avg est. cost</span><b>${{ $result->avg_estimated_cost_usd < 0.01 ? number_format($result->avg_estimated_cost_usd,6) : number_format($result->avg_estimated_cost_usd,4) }}</b></div>@endif</div>

        <div class="score-grid">@foreach($criteria as $criterion)@php($val=$scores[$criterion['key']] ?? null)<div class="score-cell {{ $val===null?'is-na':'' }}"><div><span>{{ $criterion['label'] }} <small>{{ $criterion['weight'] }}%</small></span><b>{{ $val===null?'N/A':number_format((float)$val,1) }}</b></div><div class="score-track"><i style="width:{{ (int)($val ?? 0) }}%"></i></div></div>@endforeach</div>
        @if($result->evaluator_summary)<div class="result-verdict"><i data-lucide="clipboard-check"></i><div><b>Aggregate evaluator note</b><p>{{ $result->evaluator_summary }}</p></div></div>@endif

        <div class="lab-run-stack">
            @foreach($result->runs as $run)
            @php($runScores=is_array($run->score_breakdown)?$run->score_breakdown:[])
            <details class="lab-run-detail" {{ $result->run_count===1 ? 'open' : '' }}>
                <summary><span><b>Run {{ $run->run_number }}</b><small>{{ $run->tested_at?->format('M j, Y · H:i') ?: 'Date not recorded' }}@if($run->model_version) · {{ $run->model_version }}@endif</small></span><span class="lab-run-score">{{ $run->overall_score!==null ? number_format((float)$run->overall_score,1) : '—' }}<i data-lucide="chevron-down"></i></span></summary>
                <div class="lab-run-body">
                    <div class="lab-run-scores">@foreach($criteria as $criterion)@php($runVal=$runScores[$criterion['key']] ?? null)<span><b>{{ $criterion['label'] }}</b><em>{{ $runVal===null?'N/A':number_format((float)$runVal,1) }}</em></span>@endforeach</div>
                    @if($run->evaluator_summary)<div class="lab-run-note"><b>Evaluator note</b><p>{{ $run->evaluator_summary }}</p></div>@endif
                    <div class="response-block"><div><b><i data-lucide="message-square-text"></i> Exact model response</b>@if($result->model)<a href="{{ route('models.show',$result->model) }}">Model profile <i data-lucide="arrow-up-right"></i></a>@endif</div><pre>{{ $run->response_text ?: 'Response text was not published for this run.' }}</pre></div>
                    <div class="result-metrics">@if($run->latency_ms!==null)<div><span>Latency</span><b>{{ number_format($run->latency_ms) }} ms</b></div>@endif @if($run->input_tokens!==null)<div><span>Input tokens</span><b>{{ number_format($run->input_tokens) }}</b></div>@endif @if($run->output_tokens!==null)<div><span>Output tokens</span><b>{{ number_format($run->output_tokens) }}</b></div>@endif @if($run->estimated_cost_usd!==null)<div><span>Est. cost</span><b>${{ $run->estimated_cost_usd < 0.01 ? number_format($run->estimated_cost_usd,6) : number_format($run->estimated_cost_usd,4) }}</b></div>@endif</div>
                    @if($run->evidence_url)<figure class="result-evidence"><img src="{{ $run->evidence_url }}" alt="Evidence screenshot for {{ $result->model?->name }} run {{ $run->run_number }}"><figcaption><i data-lucide="image-check"></i>Captured run evidence</figcaption></figure>@endif
                    @if($run->source_url || $run->source_label)<div class="result-source"><i data-lucide="link-2"></i><span>Evidence source:</span>@if($run->source_url)<a href="{{ $run->source_url }}" rel="nofollow noopener" target="_blank">{{ $run->source_label ?: 'Open source' }} <i data-lucide="external-link"></i></a>@else<b>{{ $run->source_label }}</b>@endif</div>@endif
                </div>
            </details>
            @endforeach
        </div>
    </article>
    @empty<div class="lab-empty"><h3>No complete model aggregates published yet</h3></div>@endforelse</div>

    <section class="lab-discussion"><div class="lab-section-head"><div><span>COMMUNITY</span><h2>Discuss this experiment</h2></div></div><div data-community-static data-community-type="test" data-community-id="{{ $test->id }}"></div></section>
</main>

<aside class="lab-detail-side">
    <div class="lab-side-card sticky"><span class="side-kicker">METHODOLOGY</span><h3>{{ $test->testTypeLabel() }} rubric</h3><p>{{ $test->methodology ?: ($test->criteria ?: 'Every model receives the same locked prompt. Each completed run is scored against the same applicable rubric, then model scores are averaged across the required runs.') }}</p><div class="method-weights">@foreach($criteria as $criterion)<div><span><b>{{ $criterion['label'] }}</b><small>{{ $criterion['description'] }}</small></span><strong>{{ $criterion['weight'] }}%</strong></div>@endforeach</div><div class="formula">Run score = weighted average of scored applicable criteria<br>Model score = average of {{ $test->required_runs }} required run{{ $test->required_runs===1?'':'s' }}</div><div class="method-na"><i data-lucide="circle-slash-2"></i><p><b>N/A rule</b><span>Missing or irrelevant criteria are excluded and remaining valid weights are normalized. No neutral filler score is inserted.</span></p></div>@if($test->source_note)<div class="method-note"><i data-lucide="shield-check"></i><p><b>Verification note</b><span>{{ $test->source_note }}</span></p></div>@endif</div>
    <div class="lab-side-card"><span class="side-kicker">EXPERIMENT STATUS</span><div class="status-row"><span>Protocol</span><b>{{ $test->runModeLabel() }}</b></div><div class="status-row"><span>Required runs/model</span><b>{{ $test->required_runs }}</b></div><div class="status-row"><span>Prompt locked</span><b>{{ $test->prompt_locked_at?->format('M j, Y') ?: 'Before publication' }}</b></div><div class="status-row"><span>Method verified</span><b>{{ $test->is_verified ? 'Yes' : 'Not marked' }}</b></div><div class="status-row"><span>Last verified</span><b>{{ $test->last_verified_at?->format('M j, Y') ?: '—' }}</b></div><div class="status-row"><span>Complete models</span><b>{{ $results->count() }}</b></div><a class="lab-method-link" href="{{ route('methodology') }}#testlab">Read AI Hub methodology <i data-lucide="arrow-right"></i></a></div>
    @if($related->count())<div class="lab-side-card"><span class="side-kicker">RELATED TESTS</span><h3>More experiments</h3>@foreach($related as $item)<a class="related-test" href="{{ route('testlab.show',$item) }}"><span>{{ $item->testTypeLabel() }}</span><b>{{ $item->name }}</b><small>{{ $item->results_count }} model results <i data-lucide="arrow-right"></i></small></a>@endforeach</div>@endif
</aside></div></div></section>
@endsection
@push('scripts')<script src="{{ asset('js/frontend/testlab.js') }}"></script>@endpush
