@extends('frontend.layouts.app')
@section('title',$test->seo_title)
@section('meta_description',$test->seo_description)
@push('head')
<link rel="canonical" href="{{ route('testlab.show',$test) }}">
<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">
<meta property="og:type" content="article"><meta property="og:title" content="{{ $test->seo_title }}"><meta property="og:description" content="{{ $test->seo_description }}"><meta property="og:url" content="{{ route('testlab.show',$test) }}">
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Dataset','name'=>$test->name,'description'=>$test->seo_description,'url'=>route('testlab.show',$test),'datePublished'=>optional($test->published_at)->toIso8601String(),'dateModified'=>optional($test->updated_at)->toIso8601String(),'measurementTechnique'=>'Shared prompt with weighted human-scored criteria','variableMeasured'=>collect($criteria)->map(fn($c,$k)=>['@type'=>'PropertyValue','name'=>$c['label'],'description'=>$c['description'],'valueReference'=>($weights[$k]??0).'% weight'])->values()->all(),'creator'=>['@type'=>'Organization','name'=>'AI Hub']], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
@endpush
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/testlab.css') }}">@endpush
@section('content')
<section class="lab-detail-hero"><div class="lab-wrap"><a class="lab-back" href="{{ route('testlab.index') }}"><i data-lucide="arrow-left"></i> AI Test Lab</a><div class="lab-detail-title"><div><div class="lab-detail-badges"><span>{{ strtoupper($test->category ?: 'GENERAL') }}</span><span>{{ strtoupper(config('test_lab.difficulties.'.$test->difficulty, ucfirst($test->difficulty))) }}</span>@if($test->is_verified)<span class="verified"><i data-lucide="badge-check"></i> VERIFIED METHODOLOGY</span>@endif</div><h1>{{ $test->name }}</h1><p>{{ $test->short_description ?: ($test->criteria ?: 'Controlled model experiment with transparent weighted scoring.') }}</p><div class="lab-detail-meta">@if($test->feature)<a href="{{ route('features.show',$test->feature) }}"><i data-lucide="sparkles"></i>{{ $test->feature->name }}</a>@endif @if($test->useCase)<a href="{{ route('use-cases.show',$test->useCase) }}"><i data-lucide="target"></i>{{ $test->useCase->name }}</a>@endif<span><i data-lucide="layers-3"></i>{{ $results->count() }} complete results</span><span><i data-lucide="calendar-check"></i>{{ ($test->published_at ?: $test->created_at)->format('M j, Y') }}</span></div></div>@if($winner)<div class="winner-badge"><span>TOP RESULT</span><img src="{{ $winner->model?->logo_url ?: asset('favicon.ico') }}" alt=""><b>{{ $winner->model?->name ?? 'Model' }}</b><strong>{{ number_format((float)$winner->overall_score,1) }}</strong><small>weighted score /100</small>@if($winner->is_verified)<em><i data-lucide="badge-check"></i>Verified result</em>@endif</div>@endif</div></div></section>

<section class="lab-detail"><div class="lab-wrap"><div class="lab-detail-grid"><main>
    <div class="lab-panel prompt-panel"><div class="lab-panel-head"><span><i data-lucide="terminal-square"></i> SHARED TEST PROMPT</span><button type="button" data-copy-prompt><i data-lucide="copy"></i>Copy</button></div><pre data-prompt-text>{{ $test->prompt }}</pre>@if($test->expected_output)<div class="expected"><b>Expected output / answer key</b><p>{{ $test->expected_output }}</p></div>@endif</div>

    <div class="lab-section-head"><div><span>RESULT EVIDENCE</span><h2>Model performance</h2><p>Only complete results are included in public scoring.</p></div><small>{{ $results->count() }} models tested</small></div>
    <div class="result-stack">@forelse($results as $i=>$result)<article class="result-card">
        <div class="result-head"><span class="result-position">#{{ $i+1 }}</span><div class="result-logo"><img src="{{ $result->model?->logo_url ?: asset('favicon.ico') }}" alt=""></div><div class="result-model"><h3>{{ $result->model?->name ?? 'Unknown model' }}</h3><p>{{ $result->model?->company?->name ?? 'AI model' }}@if($result->model_version) · {{ $result->model_version }}@endif</p></div>@if($result->is_verified)<span class="result-verified"><i data-lucide="badge-check"></i>Verified</span>@endif<div class="result-score"><strong>{{ number_format((float)$result->overall_score,1) }}</strong><span>/100</span></div></div>
        <div class="score-grid">@foreach($criteria as $key=>$criterion)@php($val=$result->{$criterion['field']})<div class="score-cell"><div><span>{{ $criterion['label'] }} <small>{{ $weights[$key] ?? 0 }}%</small></span><b>{{ $val===null?'—':$val }}</b></div><div class="score-track"><i style="width:{{ (int)($val ?? 0) }}%"></i></div></div>@endforeach</div>
        @if($result->evaluator_summary)<div class="result-verdict"><i data-lucide="clipboard-check"></i><div><b>Evaluator note</b><p>{{ $result->evaluator_summary }}</p></div></div>@endif
        <div class="result-metrics">
            @if($result->latency_ms!==null)<div><span>Latency</span><b>{{ number_format($result->latency_ms) }} ms</b></div>@endif
            @if($result->input_tokens!==null)<div><span>Input tokens</span><b>{{ number_format($result->input_tokens) }}</b></div>@endif
            @if($result->output_tokens!==null)<div><span>Output tokens</span><b>{{ number_format($result->output_tokens) }}</b></div>@endif
            @if($result->estimated_cost_usd!==null)<div><span>Est. cost</span><b>${{ $result->estimated_cost_usd < 0.01 ? number_format($result->estimated_cost_usd,6) : number_format($result->estimated_cost_usd,4) }}</b></div>@endif
            @if($result->tested_at)<div><span>Tested</span><b>{{ $result->tested_at->format('M j, Y') }}</b></div>@endif
        </div>
        <div class="response-block"><div><b><i data-lucide="message-square-text"></i> Model response</b>@if($result->model)<a href="{{ route('models.show',$result->model) }}">Model profile <i data-lucide="arrow-up-right"></i></a>@endif</div><pre>{{ $result->response_text ?: 'Response text was not published for this result.' }}</pre></div>
        @if($result->evidence_url)<figure class="result-evidence"><img src="{{ $result->evidence_url }}" alt="Evidence screenshot for {{ $result->model?->name }}"><figcaption><i data-lucide="image-check"></i>Captured evidence</figcaption></figure>@endif
        @if($result->source_url || $result->source_label)<div class="result-source"><i data-lucide="link-2"></i><span>Evidence source:</span>@if($result->source_url)<a href="{{ $result->source_url }}" rel="nofollow noopener" target="_blank">{{ $result->source_label ?: 'Open source' }} <i data-lucide="external-link"></i></a>@else<b>{{ $result->source_label }}</b>@endif</div>@endif
    </article>@empty<div class="lab-empty"><h3>No complete results published yet</h3></div>@endforelse</div>

    <section class="lab-discussion"><div class="lab-section-head"><div><span>COMMUNITY</span><h2>Discuss this experiment</h2></div></div><div data-community-static data-community-type="test" data-community-id="{{ $test->id }}"></div></section>
</main>

<aside class="lab-detail-side">
    <div class="lab-side-card sticky"><span class="side-kicker">METHODOLOGY</span><h3>Scoring framework</h3><p>{{ $test->methodology ?: ($test->criteria ?: 'Each model receives the same prompt. Available criteria are scored 0–100 and combined using the published weights below.') }}</p><div class="method-weights">@foreach($criteria as $key=>$criterion)<div><span><b>{{ $criterion['label'] }}</b><small>{{ $criterion['description'] }}</small></span><strong>{{ $weights[$key] ?? 0 }}%</strong></div>@endforeach</div><div class="formula">Overall = weighted average of scored criteria</div>@if($test->source_note)<div class="method-note"><i data-lucide="shield-check"></i><p><b>Verification note</b><span>{{ $test->source_note }}</span></p></div>@endif</div>
    <div class="lab-side-card"><span class="side-kicker">EXPERIMENT STATUS</span><div class="status-row"><span>Published</span><b>{{ $test->published_at?->format('M j, Y') ?: '—' }}</b></div><div class="status-row"><span>Method verified</span><b>{{ $test->is_verified ? 'Yes' : 'Not marked' }}</b></div><div class="status-row"><span>Last verified</span><b>{{ $test->last_verified_at?->format('M j, Y') ?: '—' }}</b></div><div class="status-row"><span>Complete results</span><b>{{ $results->count() }}</b></div><a class="lab-method-link" href="{{ route('methodology') }}#testlab">Read AI Hub methodology <i data-lucide="arrow-right"></i></a></div>
    @if($related->count())<div class="lab-side-card"><span class="side-kicker">RELATED TESTS</span><h3>More experiments</h3>@foreach($related as $item)<a class="related-test" href="{{ route('testlab.show',$item) }}"><span>{{ $item->category ?: 'General' }}</span><b>{{ $item->name }}</b><small>{{ $item->results_count }} model results <i data-lucide="arrow-right"></i></small></a>@endforeach</div>@endif
</aside></div></div></section>
@endsection
@push('scripts')<script src="{{ asset('js/frontend/testlab.js') }}"></script>@endpush
