@extends('frontend.layouts.app')
@section('title',($review->verdict ?: $review->tool?->name.' Review').' | AI Hub')
@section('meta_description',\Illuminate\Support\Str::limit($review->body ?: 'Independent AI Hub review of '.$review->tool?->name,155))
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/content.css') }}">@endpush
@section('content')
@php $tool=$review->tool; $logo=$tool?->logo_path&&file_exists(public_path($tool->logo_path))?asset($tool->logo_path):asset('favicon.ico'); $pros=collect($review->pros ?? [])->filter(); $cons=collect($review->cons ?? [])->filter(); $breakdown=collect($review->rating_breakdown ?? []); @endphp
<section class="review-detail-hero"><div class="content-wrap"><div class="content-breadcrumb"><a href="{{ route('home') }}">Home</a><i data-lucide="chevron-right"></i><a href="{{ route('reviews.index') }}">Reviews</a><i data-lucide="chevron-right"></i><span>{{ $tool?->name }}</span></div><div class="review-detail-main"><div class="review-product-id"><img src="{{ $logo }}" alt="{{ $tool?->name }} logo"><div><span class="review-type type-{{ $review->review_type }}">{{ $review->review_type==='editorial'?'AI Hub Editorial':'Community Review' }}</span><h1>{{ $review->verdict ?: $tool?->name.' Review' }}</h1><p>{{ $tool?->name }} · {{ $tool?->company?->name }} · reviewed {{ $review->created_at->format('M j, Y') }}</p></div></div><div class="review-score"><strong>{{ number_format((float)$review->rating,1) }}</strong><span>★★★★★</span><small>out of 5.0</small></div></div></div></section>
<section class="review-detail-body"><div class="content-wrap review-reading-grid"><main><div class="review-verdict-box"><span>VERDICT</span><h2>{{ $review->verdict ?: 'Published user assessment' }}</h2><p>{{ $review->body ?: 'This published review contains a rating for the tool without an additional written assessment.' }}</p></div>
@if($breakdown->isNotEmpty())<section class="review-breakdown"><div class="block-heading"><span>SCORECARD</span><h2>Rating breakdown</h2></div><div class="score-grid">@foreach($breakdown as $label=>$score)<div><span>{{ ucwords(str_replace('_',' ',$label)) }}</span><strong>{{ number_format((float)$score,1) }}</strong><div><i style="width:{{ min(100,max(0,((float)$score/5)*100)) }}%"></i></div></div>@endforeach</div></section>@endif
@if($pros->isNotEmpty() || $cons->isNotEmpty())<div class="pros-cons"><section><span class="positive"><i data-lucide="circle-check-big"></i> Strengths</span>@forelse($pros as $pro)<p><i data-lucide="check"></i>{{ $pro }}</p>@empty<p>No structured strengths were supplied.</p>@endforelse</section><section><span class="negative"><i data-lucide="circle-minus"></i> Trade-offs</span>@forelse($cons as $con)<p><i data-lucide="minus"></i>{{ $con }}</p>@empty<p>No structured trade-offs were supplied.</p>@endforelse</section></div>@endif
<section class="review-tool-cta"><img src="{{ $logo }}" alt=""><div><small>EXPLORE THE PRODUCT</small><h3>{{ $tool?->name }}</h3><p>{{ \Illuminate\Support\Str::limit($tool?->description,120) }}</p></div><a href="{{ route('tools.show',$tool) }}">Full tool profile <i data-lucide="arrow-right"></i></a></section>
@if($relatedReviews->isNotEmpty())<section><div class="block-heading"><span>MORE REVIEWS</span><h2>Related assessments</h2></div><div class="related-review-grid">@foreach($relatedReviews as $related)<a href="{{ route('reviews.show',$related) }}"><span>★ {{ number_format((float)$related->rating,1) }}</span><h3>{{ $related->verdict ?: $related->tool?->name.' review' }}</h3><p>{{ \Illuminate\Support\Str::limit($related->body,95) }}</p><small>{{ $related->tool?->name }} · {{ $related->created_at->diffForHumans() }}</small></a>@endforeach</div></section>@endif</main>
<aside class="article-aside"><div class="side-card"><span class="side-label">REVIEW SNAPSHOT</span><div class="review-snapshot"><div><span>This review</span><strong>{{ number_format((float)$review->rating,1) }}/5</strong></div><div><span>{{ $tool?->name }} average</span><strong>{{ number_format((float)($toolReviewStats->average ?? 0),1) }}/5</strong></div><div><span>Published reviews</span><strong>{{ (int)($toolReviewStats->total ?? 0) }}</strong></div></div></div><div class="side-card"><span class="side-label">REVIEWER</span><h3>{{ $review->user?->name ?? 'AI Hub Editorial' }}</h3><p>{{ $review->review_type==='editorial' ? 'Editorial review produced through AI Hub content workflow.' : 'Moderated community review published through AI Hub.' }}</p></div>@auth<a class="write-review-cta" href="{{ route('reviews.create',$tool) }}"><i data-lucide="pen-line"></i><span><strong>Used {{ $tool?->name }}?</strong><small>Write or update your review</small></span><i data-lucide="arrow-right"></i></a>@endauth</aside></div></section>
@endsection
