@extends('frontend.layouts.app')
@section('title',$topic->meta_title ?: $topic->name.' — AI Hub')
@section('meta_description',$topic->meta_description ?: $topic->short_description)
@push('head')<link rel="canonical" href="{{ route('topics.show',$topic) }}"><meta name="robots" content="{{ $articles->total() > 0 ? 'index,follow,max-image-preview:large' : 'noindex,follow' }}"><script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'CollectionPage','name'=>$topic->name,'description'=>$topic->description ?: $topic->short_description,'url'=>route('topics.show',$topic)], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>@endpush
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/discovery.css') }}">@endpush
@section('content')
<section class="category-detail-hero"><div class="category-detail-inner"><div class="category-hero-main"><a class="breadcrumb-link" href="{{ route('topics.index') }}"><i data-lucide="arrow-left"></i> All Topics</a><span class="eyebrow"><i data-lucide="newspaper"></i> Editorial Topic</span><h1>{{ $topic->name }}</h1><p>{{ $topic->description ?: $topic->short_description }}</p></div><div class="category-stat-board"><span><strong>{{ number_format($articles->total()) }}</strong><small>Published articles</small></span></div></div></section>
<div class="discovery-page category-detail-page"><section class="result-section"><div class="section-bar"><div><span class="section-icon gold"><i data-lucide="book-open-text"></i></span><h2>Latest {{ $topic->name }}</h2></div></div>@if($articles->count())<div class="mini-story-list taxonomy-story-grid">@foreach($articles as $article)<a href="{{ route('articles.show',$article) }}"><img src="{{ $article->featured_image_url ?: '/images/frontend/content-placeholder.svg' }}" alt="{{ $article->title }}"><div><small>{{ optional($article->published_at)->format('M j, Y') }} · {{ $article->company?->name ?? 'AI Hub' }}</small><h3>{{ $article->title }}</h3><p>{{ \Illuminate\Support\Str::limit($article->summary ?: strip_tags($article->content),120) }}</p></div></a>@endforeach</div><div class="category-pagination">{{ $articles->links() }}</div>@else<div class="inline-empty"><i data-lucide="book-open"></i><div><h3>No published articles yet</h3><p>This editorial topic is ready for future content.</p></div></div>@endif</section></div>
@endsection
