@extends('layouts.admin')
@section('title','Taxonomy v2')
@push('styles')<link rel="stylesheet" href="{{ asset('css/pages/final-polish.css') }}">@endpush
@section('content')
@php
$labels=[
    'categories'=>'Product Categories','subcategories'=>'Subcategories','features'=>'Features',
    'use-cases'=>'Use Cases','tags'=>'Tags','content-topics'=>'Content Topics'
];
$icons=['categories'=>'folder-tree','subcategories'=>'git-branch','features'=>'sparkles','use-cases'=>'target','tags'=>'tags','content-topics'=>'newspaper'];
$single=['categories'=>'Category','subcategories'=>'Subcategory','features'=>'Feature','use-cases'=>'Use Case','tags'=>'Tag','content-topics'=>'Content Topic'];
$isIndexableDefault=$tab!=='tags';
@endphp
<div class="fp-page">
<x-page-header title="AI Management Taxonomy v2" subtitle="SEO-aware product, capability, use-case and editorial taxonomy shared across AI Orbit." :breadcrumb="['AI Management',$labels[$tab]]">
    <x-slot:actions><span class="fp-state is-good"><i data-lucide="network"></i> Normalized taxonomy</span></x-slot:actions>
</x-page-header>
@if(session('status'))<div class="alert alert-success fp-flash"><i data-lucide="check-circle-2"></i><span>{{ session('status') }}</span></div>@endif
@if($errors->any())<div class="alert alert-danger fp-flash"><i data-lucide="circle-alert"></i><span>{{ $errors->first() }}</span></div>@endif
<nav class="fp-tabs">@foreach($labels as $key=>$label)<a href="{{ route('admin.taxonomy.'.$key) }}" class="{{ $tab===$key?'is-active':'' }}"><i data-lucide="{{ $icons[$key] }}"></i>{{ $label }}</a>@endforeach</nav>

<section class="fp-taxonomy-grid fp-taxonomy-grid--v2">
<aside class="card fp-taxonomy-create fp-taxonomy-create--v2">
    <span class="fp-eyebrow">New {{ $single[$tab] }}</span>
    <div class="fp-taxonomy-create__icon"><i data-lucide="{{ $icons[$tab] }}"></i></div>
    <h2>Add {{ strtolower($single[$tab]) }}</h2>
    <p>Use a clear human-readable name. SEO fields can be edited now or generated by the v2 sync command.</p>
    <form action="{{ route('admin.taxonomy.store',$tab) }}" method="POST" class="fp-taxonomy-v2-form">@csrf
        @if($tab==='subcategories')
            <label class="fp-field"><span>Parent category *</span><select class="select" name="category_id" required><option value="">Choose category</option>@foreach($productCategories as $category)<option value="{{ $category->id }}" @selected((string)old('category_id')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></label>
        @endif
        <label class="fp-field"><span>Name *</span><input class="input" name="name" value="{{ old('name') }}" placeholder="{{ $single[$tab] }} name" required></label>
        @if(in_array($tab,['features','use-cases']))
            @if($tab==='features')<label class="fp-field"><span>Feature group</span><input class="input" name="group" value="{{ old('group') }}" placeholder="Language, Vision, Agents..."></label>@endif
            <label class="fp-field"><span>Lucide icon</span><input class="input" name="icon" value="{{ old('icon') }}" placeholder="sparkles"></label>
        @endif
        <label class="fp-field"><span>Short description</span><textarea class="input" name="short_description" rows="3" maxlength="500" placeholder="Concise discovery description">{{ old('short_description') }}</textarea></label>
        <label class="fp-field"><span>Full description</span><textarea class="input" name="description" rows="4" maxlength="5000" placeholder="Useful, unique description for discovery and SEO">{{ old('description') }}</textarea></label>
        <label class="fp-field"><span>SEO title</span><input class="input" name="meta_title" maxlength="80" value="{{ old('meta_title') }}"></label>
        <label class="fp-field"><span>Meta description</span><textarea class="input" name="meta_description" rows="3" maxlength="180">{{ old('meta_description') }}</textarea></label>
        <div class="fp-taxonomy-v2-inline"><label class="fp-field"><span>Sort</span><input class="input" type="number" min="0" name="sort_order" value="{{ old('sort_order',0) }}"></label></div>
        <label class="fp-toggle"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',1))><span><strong>Active</strong><small>Available in admin selectors.</small></span></label>
        <label class="fp-toggle"><input type="checkbox" name="is_indexable" value="1" @checked(old('is_indexable',$isIndexableDefault))><span><strong>Indexable</strong><small>Eligible for public SEO discovery pages.</small></span></label>
        <button class="btn btn-primary fp-full"><i data-lucide="plus"></i>Add {{ $single[$tab] }}</button>
    </form>
    <div class="fp-taxonomy-note"><i data-lucide="shield-check"></i><span>Category/subcategory deletion is blocked while records still use the term. Feature, tag and use-case relations detach safely.</span></div>
</aside>

<main class="card fp-table-card">
    <header class="fp-card-head"><div><span class="fp-eyebrow">{{ $labels[$tab] }}</span><h2>Taxonomy registry</h2><p>{{ $terms->count() }} controlled term(s). Usage includes every supported entity type.</p></div><span class="fp-count">{{ $terms->count() }}</span></header>
    @if($terms->count())
        <div class="fp-taxonomy-list fp-taxonomy-list--v2">
        @foreach($terms as $term)
            <article class="fp-taxonomy-record">
                <div class="fp-taxonomy-record__head">
                    <span class="fp-taxonomy-term"><i data-lucide="{{ $term->icon ?? $icons[$tab] }}"></i></span>
                    <div class="fp-taxonomy-record__identity"><strong>{{ $term->name }}</strong><small>{{ $term->slug }}@if($tab==='subcategories' && $term->category) · {{ $term->category->name }}@endif @if($tab==='features' && $term->group) · {{ $term->group }}@endif</small></div>
                    <div class="fp-taxonomy-usage-chips">
                        @foreach($term->usage as $key=>$count)@if($key!=='total' && $count)<span>{{ ucfirst($key) }} {{ $count }}</span>@endif @endforeach
                        <span class="fp-usage"><i data-lucide="link-2"></i>{{ $term->usage_count }} total</span>
                    </div>
                    <span class="fp-state {{ $term->is_active ? 'is-good':'is-bad' }}">{{ $term->is_active ? 'Active':'Inactive' }}</span>
                    @if($term->is_indexable)<span class="fp-state is-good">SEO</span>@else<span class="fp-state">Noindex</span>@endif
                </div>
                <details class="fp-taxonomy-details">
                    <summary><i data-lucide="settings-2"></i>Edit taxonomy & SEO</summary>
                    <form method="POST" action="{{ route('admin.taxonomy.update',[$tab,$term->id]) }}" class="fp-taxonomy-edit-v2">@csrf @method('PUT')
                        @if($tab==='subcategories')<label class="fp-field"><span>Parent category</span><select class="select" name="category_id" required>@foreach($productCategories as $category)<option value="{{ $category->id }}" @selected((int)$term->category_id===(int)$category->id)>{{ $category->name }}</option>@endforeach</select></label>@endif
                        <label class="fp-field"><span>Name</span><input class="input" name="name" value="{{ $term->name }}" required></label>
                        @if($tab==='features')<label class="fp-field"><span>Group</span><input class="input" name="group" value="{{ $term->group }}"></label>@endif
                        @if(in_array($tab,['features','use-cases']))<label class="fp-field"><span>Icon</span><input class="input" name="icon" value="{{ $term->icon }}"></label>@endif
                        <label class="fp-field fp-field--full"><span>Short description</span><textarea class="input" name="short_description" rows="2" maxlength="500">{{ $term->short_description }}</textarea></label>
                        <label class="fp-field fp-field--full"><span>Full description</span><textarea class="input" name="description" rows="3">{{ $term->description }}</textarea></label>
                        <label class="fp-field"><span>SEO title</span><input class="input" name="meta_title" maxlength="80" value="{{ $term->meta_title }}"></label>
                        <label class="fp-field"><span>Meta description</span><textarea class="input" name="meta_description" rows="2" maxlength="180">{{ $term->meta_description }}</textarea></label>
                        <label class="fp-field"><span>Sort order</span><input class="input" type="number" min="0" name="sort_order" value="{{ $term->sort_order }}"></label>
                        <label class="fp-toggle"><input type="checkbox" name="is_active" value="1" @checked($term->is_active)><span><strong>Active</strong><small>Show in selectors</small></span></label>
                        <label class="fp-toggle"><input type="checkbox" name="is_indexable" value="1" @checked($term->is_indexable)><span><strong>Indexable</strong><small>SEO discovery page</small></span></label>
                        <div class="fp-taxonomy-edit-v2__actions"><button class="btn btn-secondary btn-sm"><i data-lucide="save"></i>Save changes</button></div>
                    </form>
                </details>
                <form method="POST" action="{{ route('admin.taxonomy.destroy',[$tab,$term->id]) }}" class="fp-taxonomy-delete" onsubmit="return confirm('Delete {{ addslashes($term->name) }}? Connected category/subcategory records must be reassigned first.')">@csrf @method('DELETE')<button class="btn btn-ghost btn-sm"><i data-lucide="trash-2"></i>Delete</button></form>
            </article>
        @endforeach
        </div>
    @else
        <div class="fp-empty"><span><i data-lucide="{{ $icons[$tab] }}"></i></span><h3>No taxonomy terms yet</h3><p>Run <code>php artisan taxonomy:v2-sync</code> or add a term from the panel.</p></div>
    @endif
</main>
</section>
</div>
@endsection
