@extends('layouts.admin')
@section('title','Taxonomy')
@section('content')
@php $labels=['categories'=>'Categories','subcategories'=>'Subcategories','features'=>'Features','tags'=>'Tags']; @endphp
<x-page-header title="AI Management Taxonomy" subtitle="Database-driven categories, subcategories, features and tags" :breadcrumb="['AI Management',$labels[$tab]]" />
@if(session('status'))<div class="alert alert-success" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger" style="margin-bottom:16px;">{{ $errors->first() }}</div>@endif
<div class="tabs"><a class="tab {{ $tab==='categories'?'is-active':'' }}" href="{{ route('admin.taxonomy.categories') }}">Categories</a><a class="tab {{ $tab==='subcategories'?'is-active':'' }}" href="{{ route('admin.taxonomy.subcategories') }}">Subcategories</a><a class="tab {{ $tab==='features'?'is-active':'' }}" href="{{ route('admin.taxonomy.features') }}">Features</a><a class="tab {{ $tab==='tags'?'is-active':'' }}" href="{{ route('admin.taxonomy.tags') }}">Tags</a></div>
<div class="card card-pad" style="margin-bottom:16px;"><form action="{{ route('admin.taxonomy.store',$tab) }}" method="POST" class="flex gap-8">@csrf<input class="input" name="name" placeholder="New {{ rtrim($labels[$tab],'s') }} name" required style="flex:1"><button class="btn btn-primary btn-sm"><i data-lucide="plus"></i> Add</button></form><div class="text-sub" style="margin-top:8px;">Names are unique. Renames safely update connected tools; deleting a term detaches it without deleting tools.</div></div>
<div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Usage</th><th>Actions</th></tr></thead><tbody>@forelse($terms as $term)<tr><td><form class="flex gap-8" method="POST" action="{{ route('admin.taxonomy.update',[$tab,$term->id]) }}">@csrf @method('PUT')<input class="input" name="name" value="{{ $term->name }}" style="max-width:320px"><button class="btn btn-secondary btn-sm">Save</button></form></td><td class="mono">{{ $term->usage_count }}</td><td><form method="POST" action="{{ route('admin.taxonomy.destroy',[$tab,$term->id]) }}" onsubmit="return confirm('Delete this taxonomy term? Connected tools will remain safe.')">@csrf @method('DELETE')<button class="icon-btn"><i data-lucide="trash-2"></i></button></form></td></tr>@empty<tr><td colspan="3" style="text-align:center;padding:32px;">No terms yet.</td></tr>@endforelse</tbody></table></div></div>
@endsection
