@extends('layouts.admin')
@section('title','AI Tools')
@section('content')
<x-page-header title="AI Tools" subtitle="Manage, filter and publish your AI tool directory" :breadcrumb="['AI Management','AI Tools']"><x-slot:actions>@if(auth()->user()->canAccessModule('AI Tools','Add'))<a href="{{ route('admin.tools.create') }}" class="btn btn-primary btn-sm"><i data-lucide="plus"></i> Add Tool</a>@endif</x-slot:actions></x-page-header>
@if(session('status'))<div class="alert alert-success" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
<form method="GET" class="card card-pad" style="margin-bottom:16px;display:grid;grid-template-columns:2fr repeat(5,minmax(130px,1fr)) auto auto;gap:8px;">
<input class="input" name="search" value="{{ request('search') }}" placeholder="Search tools...">
<select class="select" name="category_id"><option value="">All Categories</option>@foreach($categories as $c)<option value="{{ $c->id }}" @selected((string)request('category_id')===(string)$c->id)>{{ $c->name }}</option>@endforeach</select>
<select class="select" name="company_id"><option value="">All Companies</option>@foreach($companies as $c)<option value="{{ $c->id }}" @selected((string)request('company_id')===(string)$c->id)>{{ $c->name }}</option>@endforeach</select>
<select class="select" name="pricing"><option value="">All Pricing</option>@foreach(['Free','Freemium','Paid','Enterprise'] as $p)<option value="{{ $p }}" @selected(request('pricing')===$p)>{{ $p }}</option>@endforeach</select>
<select class="select" name="status"><option value="">All Status</option>@foreach(['draft'=>'Draft','published'=>'Published','archived'=>'Archived'] as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select>
<select class="select" name="rating"><option value="">Any Rating</option><option value="4" @selected(request('rating')==='4')>4+ Stars</option><option value="3" @selected(request('rating')==='3')>3+ Stars</option></select>
<button class="btn btn-secondary btn-sm">Filter</button><a href="{{ route('admin.tools.index') }}" class="btn btn-secondary btn-sm">Reset</a>
</form>
<div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Tool</th><th>Company</th><th>Category</th><th>Subcategory</th><th>Models</th><th>Rating</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($tools as $tool)<tr><td><a href="{{ route('admin.tools.show',$tool->id) }}"><b>{{ $tool->name }}</b></a><div class="cell-sub">{{ $tool->short_description ?: $tool->slug }}</div></td><td>{{ $tool->company?->name ?? '—' }}</td><td>{{ $tool->category?->name ?? '—' }}</td><td>{{ $tool->subcategoryTerm?->name ?? $tool->subcategory ?? '—' }}</td><td class="mono">{{ $tool->models_count }}</td><td class="mono">{{ number_format((float)$tool->rating,1) }}</td><td><x-status-badge status="{{ ucfirst($tool->status) }}" type="{{ $tool->status==='published'?'pos':($tool->status==='draft'?'warn':'neutral') }}" /></td><td><div class="flex gap-8">@if(auth()->user()->canAccessModule('AI Tools','Edit'))<a class="icon-btn" href="{{ route('admin.tools.edit',$tool->id) }}" title="Edit"><i data-lucide="pencil"></i></a>@endif @if(auth()->user()->canAccessModule('AI Tools','Delete'))<form method="POST" action="{{ route('admin.tools.destroy',$tool->id) }}" onsubmit="return confirm('Delete this tool? Linked models will be kept but detached.')">@csrf @method('DELETE')<button class="icon-btn" title="Delete"><i data-lucide="trash-2"></i></button></form>@endif</div></td></tr>@empty<tr><td colspan="8" style="text-align:center;padding:32px;">No tools found.</td></tr>@endforelse
</tbody></table></div><div class="pager"><span>Showing {{ $tools->firstItem() ?? 0 }}–{{ $tools->lastItem() ?? 0 }} of {{ $tools->total() }}</span><div class="pager-btns">{{ $tools->links() }}</div></div></div>
@endsection
