@extends('layouts.admin')
@section('title',$tool->name.' · AI Tool')
@section('content')
<x-page-header title="{{ $tool->name }}" subtitle="Tool profile, taxonomy, models and quality signals" :breadcrumb="['AI Management','AI Tools',$tool->name]"><x-slot:actions><a href="{{ route('admin.tools.edit',$tool->id) }}" class="btn btn-primary btn-sm"><i data-lucide="pencil"></i> Edit Tool</a></x-slot:actions></x-page-header>
@if(session('status'))<div class="alert alert-success" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
<div class="kpi-grid" style="grid-template-columns:repeat(4,1fr);margin-bottom:16px;"><x-kpi-card icon="star" label="Rating" value="{{ number_format((float)$tool->rating,1) }}"/><x-kpi-card icon="brain" label="Models" value="{{ $tool->models_count }}"/><x-kpi-card icon="message-square" label="Reviews" value="{{ $tool->reviews_count }}"/><x-kpi-card icon="activity" label="Status" value="{{ ucfirst($tool->status) }}"/></div>
<div class="grid-12"><div class="col-8">
<div class="card card-pad" style="margin-bottom:16px;"><h3 style="margin-top:0;">Overview</h3><p>{{ $tool->description ?: $tool->short_description ?: 'No description yet.' }}</p><div class="flex gap-8" style="flex-wrap:wrap;">@foreach($tool->featureTerms as $f)<span class="badge badge-violet">{{ $f->name }}</span>@endforeach</div></div>
<div class="card" style="margin-bottom:16px;"><div class="card-pad"><b>Connected Models</b></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Model</th><th>Version</th><th>Status</th><th></th></tr></thead><tbody>@forelse($tool->models as $model)<tr><td>{{ $model->name }}</td><td>{{ $model->version ?: '—' }}</td><td>{{ ucfirst($model->status) }}</td><td><a href="{{ route('admin.models.show',$model->id) }}">View</a></td></tr>@empty<tr><td colspan="4" style="text-align:center;padding:24px;">No models linked.</td></tr>@endforelse</tbody></table></div></div>
</div><div class="col-4"><div class="card card-pad"><h3 style="margin-top:0;">Directory Data</h3><p><b>Company:</b> {{ $tool->company?->name ?? '—' }}</p><p><b>Category:</b> {{ $tool->category?->name ?? '—' }}</p><p><b>Subcategory:</b> {{ $tool->subcategoryTerm?->name ?? $tool->subcategory ?? '—' }}</p><p><b>Published:</b> {{ $tool->published_at?->diffForHumans() ?? 'Not published' }}</p>@if($tool->website)<a class="btn btn-secondary btn-sm" href="{{ $tool->website }}" target="_blank" rel="noopener">Visit Website</a>@endif<hr><b>Tags</b><div class="flex gap-8" style="flex-wrap:wrap;margin-top:8px;">@foreach($tool->tagTerms as $tag)<span class="badge badge-neutral">{{ $tag->name }}</span>@endforeach</div></div></div></div>
@endsection
