@extends('frontend.layouts.app')
@section('title','AI Articles, Guides & Research | AI Orbit')
@section('meta_description','Read practical AI guides, benchmark explainers, product analysis, research and workflow intelligence from AI Orbit.')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/content.css') }}">@endpush
@section('content')
<section class="content-hero"><div class="content-wrap">
    <span class="content-eyebrow"><i data-lucide="book-open-text"></i> AI ORBIT EDITORIAL</span>
    <h1>Understand AI beyond <span>the headlines.</span></h1>
    <p>Practical guides, product analysis, benchmark explainers and research designed to help you make better AI decisions.</p>
    <form class="content-search" method="GET" action="{{ route('articles.index') }}"><i data-lucide="search"></i><input name="q" value="{{ request('q') }}" placeholder="Search guides, benchmarks, products, research..."><button>Search articles</button></form>
    <div class="content-stats"><div><strong>{{ number_format($stats['articles']) }}</strong><span>Published articles</span></div><div><strong>{{ number_format($stats['guides']) }}</strong><span>Practical guides</span></div><div><strong>{{ number_format($stats['companies']) }}</strong><span>Companies covered</span></div></div>
</div></section>

<section class="content-directory"><div class="content-wrap">
    @if($featured)
    <a class="featured-article" href="{{ route('articles.show',$featured) }}"><div class="featured-media"><img src="{{ $featured->featured_image_url ?: '/images/frontend/content-placeholder.svg' }}" alt="{{ $featured->title }}"><span>{{ $featured->category ?: 'Featured' }}</span></div><div class="featured-copy"><small>FEATURED INTELLIGENCE</small><h2>{{ $featured->title }}</h2><p>{{ $featured->summary ?: \Illuminate\Support\Str::limit(strip_tags($featured->content),180) }}</p><div class="article-meta"><span><i data-lucide="building-2"></i>{{ $featured->company?->name ?? 'AI Orbit' }}</span><span><i data-lucide="calendar-days"></i>{{ optional($featured->published_at)->format('M j, Y') }}</span><span><i data-lucide="clock-3"></i>{{ max(1,(int)ceil(str_word_count(strip_tags($featured->content ?? $featured->summary ?? ''))/220)) }} min read</span></div><b>Read featured article <i data-lucide="arrow-right"></i></b></div></a>
    @endif

    <div class="content-toolbar"><div><span class="content-kicker">KNOWLEDGE LIBRARY</span><h2>Latest AI Articles</h2><p>{{ number_format($articles->total()) }} results</p></div><div class="content-toolbar-actions"><button class="content-filter-open" type="button" data-content-filter-open><i data-lucide="sliders-horizontal"></i> Filters</button><form method="GET">@foreach(request()->except('sort','page') as $k=>$v)<input type="hidden" name="{{ $k }}" value="{{ $v }}">@endforeach<select name="sort" onchange="this.form.submit()"><option value="newest">Newest</option><option value="oldest" @selected(request('sort')==='oldest')>Oldest</option><option value="title" @selected(request('sort')==='title')>Title A–Z</option></select></form></div></div>

    <div class="content-layout"><div class="content-overlay" data-content-overlay></div>
        <aside class="content-filters" data-content-filters><div class="content-filter-mobile"><strong>Filter articles</strong><button type="button" data-content-filter-close><i data-lucide="x"></i></button></div><form method="GET" action="{{ route('articles.index') }}">@if(request('q'))<input type="hidden" name="q" value="{{ request('q') }}">@endif<div class="content-filter-head"><strong><i data-lucide="sliders-horizontal"></i> Filters</strong><a href="{{ route('articles.index') }}">Reset</a></div><div class="content-filter-group"><h3>Category</h3>@foreach($categoryCounts as $category=>$count)<label><span><input type="radio" name="category" value="{{ $category }}" @checked(request('category')===$category)>{{ $category }}</span><b>{{ $count }}</b></label>@endforeach</div><div class="content-filter-group"><h3>Company</h3><select name="company"><option value="">All companies</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((string)request('company')===(string)$company->id)>{{ $company->name }}</option>@endforeach</select></div><button class="content-apply">Apply filters</button></form></aside>

        <div class="article-results">@if($articles->count())<div class="article-directory-grid">@foreach($articles as $article)<article class="directory-article-card"><a class="directory-article-media" href="{{ route('articles.show',$article) }}"><img src="{{ $article->featured_image_url ?: '/images/frontend/content-placeholder.svg' }}" alt="{{ $article->title }}"><span>{{ $article->category ?: 'Article' }}</span></a><div class="directory-article-copy"><div class="article-meta compact"><span>{{ $article->company?->name ?? 'AI Orbit' }}</span><span>{{ optional($article->published_at)->diffForHumans() }}</span></div><h3><a href="{{ route('articles.show',$article) }}">{{ $article->title }}</a></h3><p>{{ \Illuminate\Support\Str::limit($article->summary ?: strip_tags($article->content),135) }}</p><div class="directory-article-foot"><span><i data-lucide="clock-3"></i>{{ max(1,(int)ceil(str_word_count(strip_tags($article->content ?? $article->summary ?? ''))/220)) }} min</span><button type="button" class="save-item-btn compact" data-save-item data-save-type="article" data-save-id="{{ $article->id }}" aria-label="Save article" aria-pressed="false"><i data-lucide="bookmark"></i></button><a href="{{ route('articles.show',$article) }}">Read article <i data-lucide="arrow-right"></i></a></div></div></article>@endforeach</div>@else<div class="content-empty"><i data-lucide="book-open-text"></i><h3>No articles found</h3><p>Try clearing one or more filters.</p><a href="{{ route('articles.index') }}">Reset filters</a></div>@endif
        @if($articles->hasPages())<div class="content-pagination"><a class="{{ $articles->onFirstPage()?'disabled':'' }}" href="{{ $articles->previousPageUrl() ?: '#' }}"><i data-lucide="chevron-left"></i> Previous</a><div>@foreach(range(1,$articles->lastPage()) as $page)<a class="{{ $articles->currentPage()===$page?'active':'' }}" href="{{ $articles->url($page) }}">{{ $page }}</a>@endforeach</div><a class="{{ !$articles->hasMorePages()?'disabled':'' }}" href="{{ $articles->nextPageUrl() ?: '#' }}">Next <i data-lucide="chevron-right"></i></a></div>@endif</div>

        <aside class="content-side"><div class="side-card"><span class="side-label">TOPICS</span><h3>Explore by topic</h3>@foreach($categoryCounts->take(7) as $category=>$count)<a href="{{ route('articles.index',['category'=>$category]) }}"><span>{{ $category }}</span><b>{{ $count }}</b></a>@endforeach</div><div class="side-card editorial-card"><i data-lucide="badge-check"></i><h3>Editorial standard</h3><p>Published articles shown here have completed the AI Orbit approval workflow.</p></div></aside>
    </div>
</div></section>
@endsection
@push('scripts')<script src="{{ asset('js/frontend/content.js') }}"></script>@endpush
