@extends('frontend.layouts.app')
@section('title',($article->seo_title ?: $article->title.' | AI Hub'))
@section('meta_description',$article->meta_description ?: $article->summary ?: 'AI Hub article')
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/content.css') }}">@endpush
@section('content')
@php
$image = $article->featured_image_path && file_exists(public_path($article->featured_image_path)) ? asset($article->featured_image_path) : asset('storage/ai-hub/news/ai-research.png');
$readTime=max(1,(int)ceil(str_word_count(strip_tags($article->content ?? $article->summary ?? ''))/220));
$tags=collect($article->tags ?? [])->merge($article->tagTerms->pluck('name'))->filter()->unique();
@endphp
<section class="article-detail-hero"><div class="content-wrap"><div class="content-breadcrumb"><a href="{{ route('home') }}">Home</a><i data-lucide="chevron-right"></i><a href="{{ route('articles.index') }}">Articles</a><i data-lucide="chevron-right"></i><span>{{ \Illuminate\Support\Str::limit($article->title,45) }}</span></div><div class="article-detail-grid"><div><span class="article-category">{{ $article->category ?: $article->categoryTerm?->name ?: 'Article' }}</span><h1>{{ $article->title }}</h1><p class="article-deck">{{ $article->summary }}</p><div class="article-byline"><span><i data-lucide="user-round"></i>{{ $article->author?->name ?? 'AI Hub Editorial' }}</span><span><i data-lucide="calendar-days"></i>{{ optional($article->published_at)->format('F j, Y') }}</span><span><i data-lucide="clock-3"></i>{{ $readTime }} min read</span>@if($article->reviewer)<span><i data-lucide="badge-check"></i>Reviewed by {{ $article->reviewer->name }}</span>@endif</div></div><div class="article-detail-image"><img src="{{ $image }}" alt="{{ $article->title }}"><span><i data-lucide="shield-check"></i> Editorially approved</span></div></div></div></section>
<section class="article-reading"><div class="content-wrap article-reading-grid"><article class="article-body"><div class="article-summary-box"><span>THE BRIEF</span><p>{{ $article->summary ?: 'A practical AI Hub analysis focused on the information that matters for product and model decisions.' }}</p></div><div class="article-prose">{!! nl2br(e($article->content ?: $article->summary)) !!}</div>@if($tags->isNotEmpty())<div class="article-tags"><span>Topics</span>@foreach($tags as $tag)<a href="{{ route('articles.index',['q'=>$tag]) }}">#{{ $tag }}</a>@endforeach</div>@endif
@if($relatedTools->isNotEmpty() || $relatedModels->isNotEmpty())<section class="article-related-block"><div class="block-heading"><span>MENTIONED IN THIS ARTICLE</span><h2>Related AI products</h2></div><div class="article-product-grid">@foreach($relatedTools as $tool)@php $logo=$tool->logo_path&&file_exists(public_path($tool->logo_path))?asset($tool->logo_path):asset('favicon.ico'); @endphp<a href="{{ route('tools.show',$tool) }}"><img src="{{ $logo }}" alt=""><div><small>AI TOOL</small><strong>{{ $tool->name }}</strong><span>{{ $tool->company?->name }}</span></div><i data-lucide="arrow-up-right"></i></a>@endforeach @foreach($relatedModels as $model)@php $logo=$model->logo_path&&file_exists(public_path($model->logo_path))?asset($model->logo_path):asset('favicon.ico'); @endphp<a href="{{ route('models.show',$model) }}"><img src="{{ $logo }}" alt=""><div><small>AI MODEL</small><strong>{{ $model->name }}</strong><span>{{ $model->company?->name }}</span></div><i data-lucide="arrow-up-right"></i></a>@endforeach</div></section>@endif
<div class="article-prev-next"><div>@if($previous)<small>Previous</small><a href="{{ route('articles.show',$previous) }}"><i data-lucide="arrow-left"></i>{{ \Illuminate\Support\Str::limit($previous->title,55) }}</a>@endif</div><div>@if($next)<small>Next</small><a href="{{ route('articles.show',$next) }}">{{ \Illuminate\Support\Str::limit($next->title,55) }}<i data-lucide="arrow-right"></i></a>@endif</div></div></article>
<aside class="article-aside"><div class="side-card article-author"><span class="side-label">PUBLISHED BY</span><div class="author-avatar">{{ strtoupper(substr($article->author?->name ?? 'AI',0,2)) }}</div><h3>{{ $article->author?->name ?? 'AI Hub Editorial' }}</h3><p>AI Hub editorial content is structured around product intelligence, benchmarks and practical decision-making.</p></div>@if($article->company)<div class="side-card"><span class="side-label">COMPANY</span><h3>{{ $article->company->name }}</h3><p>{{ \Illuminate\Support\Str::limit($article->company->description,110) }}</p><a class="side-action" href="{{ route('companies.show',$article->company) }}">Company profile <i data-lucide="arrow-right"></i></a></div>@endif<div class="side-card"><span class="side-label">SHARE</span><div class="share-row"><button type="button" data-save-item data-save-type="article" data-save-id="{{ $article->id }}" aria-label="Save article" aria-pressed="false"><i data-lucide="bookmark"></i></button><button type="button" onclick="navigator.clipboard?.writeText(location.href)"><i data-lucide="link"></i></button><a href="mailto:?subject={{ rawurlencode($article->title) }}&body={{ rawurlencode(request()->fullUrl()) }}"><i data-lucide="mail"></i></a></div></div></aside></div>
@if($relatedArticles->isNotEmpty())<div class="content-wrap related-reading"><div class="block-heading"><span>KEEP READING</span><h2>Related intelligence</h2></div><div class="related-reading-grid">@foreach($relatedArticles as $related)<a href="{{ route('articles.show',$related) }}"><small>{{ $related->category ?: 'Article' }}</small><h3>{{ $related->title }}</h3><p>{{ \Illuminate\Support\Str::limit($related->summary,100) }}</p><span>{{ optional($related->published_at)->format('M j, Y') }} <i data-lucide="arrow-right"></i></span></a>@endforeach</div></div>@endif
</section>
@endsection
