@extends('layouts.admin')
@section('title','Media Library')
@push('styles')<link rel="stylesheet" href="{{ asset('css/pages/final-polish.css') }}">@endpush
@section('content')
<div class="fp-page">
<x-page-header title="Media Library" :subtitle="$totalFiles.' files · '.$totalSize.' in the current view'" :breadcrumb="['Content','Media Library']" />
@if(session('status'))<div class="alert alert-success fp-flash"><i data-lucide="check-circle-2"></i><span>{{ session('status') }}</span></div>@endif
@if($errors->has('media'))<div class="alert alert-danger fp-flash"><i data-lucide="circle-alert"></i><span>{{ $errors->first('media') }}</span></div>@endif
<form method="GET" class="card fp-media-toolbar">@if($activeFolder)<input type="hidden" name="folder" value="{{ $activeFolder }}">@endif<div class="fp-search"><i data-lucide="search"></i><input class="input" name="search" value="{{ request('search') }}" placeholder="Search media filename..."></div><div class="fp-folder-tabs"><a href="{{ route('admin.media',['search'=>request('search')]) }}" class="{{ !$activeFolder?'is-active':'' }}"><i data-lucide="folders"></i>All</a>@foreach($folders as $label=>$folder)<a href="{{ route('admin.media',['folder'=>$folder,'search'=>request('search')]) }}" class="{{ $activeFolder===$folder?'is-active':'' }}">{{ $label }}</a>@endforeach</div></form>
<section class="fp-media-summary"><div><span class="fp-eyebrow">Current View</span><strong>{{ $totalFiles }}</strong><small>Files</small></div><div><span class="fp-eyebrow">Storage</span><strong>{{ $totalSize }}</strong><small>Used in filtered view</small></div><div><span class="fp-eyebrow">Deletion Policy</span><strong>Reference-safe</strong><small>In-use files are blocked</small></div></section>
@if($files->isEmpty())<div class="card fp-empty"><span><i data-lucide="images"></i></span><h3>No media matched</h3><p>Uploads from Tools, Companies, Articles and Social Posts appear here automatically.</p></div>
@else<section class="fp-media-grid">@foreach($files as $file)<article class="card fp-media-card"><a href="{{ $file['url'] }}" target="_blank" rel="noopener noreferrer" class="fp-media-card__preview"><img src="{{ $file['url'] }}" alt="{{ $file['name'] }}"></a><div class="fp-media-card__body"><strong title="{{ $file['name'] }}">{{ $file['name'] }}</strong><small>{{ $file['size']<1024?$file['size'].' B':($file['size']<1048576?round($file['size']/1024,1).' KB':round($file['size']/1048576,1).' MB') }}</small>@if($file['usage_count']>0)<div class="fp-media-use is-used"><i data-lucide="link-2"></i>In use · {{ implode(', ',$file['used_by']) }}</div>@else<div class="fp-media-use"><i data-lucide="circle-check"></i>Unused · safe to delete</div>@endif<form action="{{ route('admin.media.destroy') }}" method="POST" onsubmit="return confirm('Delete this unused file? Files still referenced by content are blocked automatically.')">@csrf @method('DELETE')<input type="hidden" name="path" value="{{ $file['path'] }}"><button class="btn btn-ghost fp-full" {{ $file['usage_count']>0?'disabled':'' }}><i data-lucide="trash-2"></i>Delete File</button></form></div></article>@endforeach</section>@endif
</div>
@endsection
