<?php

return [
    'product_categories' => [
        ['name'=>'Chat & Assistants','slug'=>'chat-assistants','icon'=>'messages-square','legacy'=>['AI Chat','AI Assistants','Conversational AI'],'description'=>'AI assistants for general conversation, reasoning, research, productivity and multimodal everyday work.','subcategories'=>[
            'General AI Assistants','Personal AI Assistants','Enterprise Assistants','Knowledge Assistants','Customer-facing Chatbots',
        ]],
        ['name'=>'Coding & Development','slug'=>'coding-development','icon'=>'code-2','legacy'=>['AI Coding','App Builder','Developer Tools','AI Platform','AI Infrastructure'],'description'=>'AI products for software development, code generation, debugging, testing and agentic engineering workflows.','subcategories'=>[
            'Code Assistants','AI IDEs & Copilots','App Builders','Code Review & Debugging','Developer Agents','AI Developer Platforms','Testing & QA',
        ]],
        ['name'=>'Image & Design','slug'=>'image-design','icon'=>'image','legacy'=>['AI Image','Image AI','Image Editing','Design AI','Creative AI'],'description'=>'AI tools for image generation, editing, design, branding, creative production and visual workflows.','subcategories'=>[
            'Image Generators','Image Editors','Graphic Design','Logo & Brand Design','Photo Enhancement','Background & Object Editing',
        ]],
        ['name'=>'Video & Animation','slug'=>'video-animation','icon'=>'clapperboard','legacy'=>['AI Video','Video AI','AI Avatars','Video Editing','Audio & Video AI'],'description'=>'AI video creation, editing, animation, avatar and production tools for creators and teams.','subcategories'=>[
            'Video Generators','Video Editors','AI Avatars','Animation Tools','Short-form Video','Presentation Video',
        ]],
        ['name'=>'Writing & Content','slug'=>'writing-content','icon'=>'pen-line','legacy'=>['AI Writing','Writing AI'],'description'=>'AI writing, editing, content generation, SEO and publishing tools for professional and creative workflows.','subcategories'=>[
            'Writing Assistants','Copywriting','SEO Content','Editing & Proofreading','Blog & Article Writing','Script Writing',
        ]],
        ['name'=>'Voice & Audio','slug'=>'voice-audio','icon'=>'mic-2','legacy'=>['AI Voice','Voice AI'],'description'=>'AI speech, voice, transcription, dubbing and audio processing tools for communication and production.','subcategories'=>[
            'Voice & Speech Platforms','Text to Speech','Speech to Text','Voice Cloning','Dubbing & Translation','Audio Enhancement','Meeting Transcription',
        ]],
        ['name'=>'Music','slug'=>'music','icon'=>'music-2','legacy'=>['AI Music','Music AI'],'description'=>'AI products for music generation, composition, mastering, vocals and audio creativity.','subcategories'=>[
            'Music Generators','Songwriting','AI Vocals','Mixing & Mastering','Sound Effects','Music Production',
        ]],
        ['name'=>'Search & Research','slug'=>'search-research','icon'=>'search','legacy'=>['AI Search','Research AI','Enterprise Search','AI Search API','Market Intelligence','Medical Research AI','Legal AI','Finance AI'],'description'=>'AI search engines and research systems for finding, synthesizing and citing information across the web and private sources.','subcategories'=>[
            'AI Search Engines','Deep Research','Academic Research','Document Research','Market Research','Citation & Evidence Tools',
        ]],
        ['name'=>'Agents & Automation','slug'=>'agents-automation','icon'=>'workflow','legacy'=>['AI Agents','AI Automation','Robotics AI','Robotics','Autonomous AI'],'description'=>'AI agents and automation platforms that plan, execute tasks and connect tools across multi-step workflows.','subcategories'=>[
            'Autonomous Agents','Workflow Automation','Browser Agents','Computer-use Agents','Multi-agent Platforms','Agent Builders','Robotics & Autonomous Systems',
        ]],
        ['name'=>'Productivity & Office','slug'=>'productivity-office','icon'=>'zap','legacy'=>['AI Productivity','Productivity AI','Document AI','Meeting AI','Presentation AI'],'description'=>'AI productivity tools for documents, meetings, notes, presentations, scheduling and everyday knowledge work.','subcategories'=>[
            'Meeting Assistants','Note Taking','Presentations','Documents & Office','Email Assistants','Task & Calendar Assistants',
        ]],
        ['name'=>'Data & Analytics','slug'=>'data-analytics','icon'=>'chart-no-axes-combined','legacy'=>['Enterprise AI','Healthcare AI','Cybersecurity AI','AI Security'],'description'=>'AI tools for data analysis, business intelligence, spreadsheets, databases and decision support.','subcategories'=>[
            'Data Analysis','Business Intelligence','Enterprise AI Platforms','Spreadsheet AI','SQL & Database Assistants','Data Visualization','Predictive Analytics','Healthcare & Clinical AI','Security & Risk Analytics',
        ]],
        ['name'=>'Marketing & Sales','slug'=>'marketing-sales','icon'=>'megaphone','legacy'=>['Marketing AI','Sales AI'],'description'=>'AI platforms for marketing campaigns, sales enablement, advertising, lead generation and growth workflows.','subcategories'=>[
            'Marketing Automation','Sales Assistants','Ad Creative','Social Media Marketing','Lead Generation','Email Marketing',
        ]],
        ['name'=>'Customer Support','slug'=>'customer-support','icon'=>'headphones','legacy'=>['Customer Support AI','Contact Center AI','Voice Agents'],'description'=>'AI support products for service automation, help desks, conversational support and customer experience operations.','subcategories'=>[
            'Support Chatbots','Help Desk AI','Contact Center AI','Knowledge Base Support','Ticket Automation','Customer Success',
        ]],
        ['name'=>'Education & Learning','slug'=>'education-learning','icon'=>'graduation-cap','legacy'=>[],'description'=>'AI tutors, study assistants and learning tools for students, educators and professional development.','subcategories'=>[
            'AI Tutors','Study Assistants','Language Learning','Course Creation','Homework & Practice','Teacher Tools',
        ]],
    ],

    'features' => [
        ['name'=>'Text Generation','group'=>'Language','icon'=>'text','aliases'=>[],'description'=>'Generates original text from natural-language instructions or structured prompts.'],
        ['name'=>'Reasoning','group'=>'Intelligence','icon'=>'brain-circuit','aliases'=>[],'description'=>'Supports multi-step reasoning, planning, analysis and problem solving.'],
        ['name'=>'Web Browsing & Search','group'=>'Research','icon'=>'search','aliases'=>['Web Search'],'description'=>'Retrieves and synthesizes information from live or indexed web sources.'],
        ['name'=>'Deep Research','group'=>'Research','icon'=>'book-open-check','aliases'=>['Research'],'description'=>'Performs multi-source research, synthesis and evidence-oriented investigation.'],
        ['name'=>'Document & PDF Analysis','group'=>'Research','icon'=>'file-search','aliases'=>['File Analysis'],'description'=>'Reads, extracts, summarizes and answers questions over uploaded documents and PDFs.'],
        ['name'=>'Image Understanding','group'=>'Vision','icon'=>'scan-eye','aliases'=>['Vision'],'description'=>'Interprets images, screenshots, diagrams and other visual inputs.'],
        ['name'=>'Image Generation','group'=>'Vision','icon'=>'image-plus','aliases'=>['Image'],'description'=>'Creates images from text, references or structured creative instructions.'],
        ['name'=>'Image Editing','group'=>'Vision','icon'=>'wand-sparkles','aliases'=>[],'description'=>'Edits, transforms, removes or replaces visual content in images.'],
        ['name'=>'Video Understanding','group'=>'Video','icon'=>'scan-play','aliases'=>[],'description'=>'Analyzes video content, scenes, speech and temporal context.'],
        ['name'=>'Video Modality','group'=>'Video','icon'=>'video','aliases'=>['Video'],'description'=>'Accepts, produces or otherwise works with video as a first-class model modality.'],
        ['name'=>'Video Generation','group'=>'Video','icon'=>'clapperboard','aliases'=>[],'description'=>'Creates video clips or animated sequences from text, images or references.'],
        ['name'=>'Video Editing','group'=>'Video','icon'=>'film','aliases'=>[],'description'=>'Assists with cutting, transforming, enhancing or assembling video content.'],
        ['name'=>'Code Generation','group'=>'Development','icon'=>'code-2','aliases'=>[],'description'=>'Generates source code, functions, components or complete implementations.'],
        ['name'=>'Code Execution','group'=>'Development','icon'=>'terminal','aliases'=>[],'description'=>'Runs code or uses an execution environment to calculate, test or transform data.'],
        ['name'=>'Code Review & Debugging','group'=>'Development','icon'=>'bug','aliases'=>[],'description'=>'Reviews code, identifies defects and recommends or applies fixes.'],
        ['name'=>'Speech to Text','group'=>'Audio','icon'=>'audio-lines','aliases'=>[],'description'=>'Transcribes spoken audio into text.'],
        ['name'=>'Text to Speech','group'=>'Audio','icon'=>'volume-2','aliases'=>['Voice Synthesis'],'description'=>'Synthesizes spoken audio from written text.'],
        ['name'=>'Voice Cloning','group'=>'Audio','icon'=>'mic-vocal','aliases'=>[],'description'=>'Creates synthetic speech that resembles a supplied or licensed voice.'],
        ['name'=>'Audio Understanding','group'=>'Audio','icon'=>'ear','aliases'=>['Audio'],'description'=>'Analyzes speech, sound, music or other audio inputs.'],
        ['name'=>'Music Generation','group'=>'Audio','icon'=>'music','aliases'=>[],'description'=>'Generates music, songs or instrumental compositions with AI.'],
        ['name'=>'Multimodal','group'=>'Intelligence','icon'=>'panels-top-left','aliases'=>[],'description'=>'Works across multiple modalities such as text, image, audio or video.'],
        ['name'=>'Structured Outputs','group'=>'Development','icon'=>'braces','aliases'=>[],'description'=>'Returns schema-constrained JSON or other predictable structured data.'],
        ['name'=>'Function Calling','group'=>'Development','icon'=>'waypoints','aliases'=>[],'description'=>'Invokes defined functions or tools with structured arguments.'],
        ['name'=>'API Access','group'=>'Platform','icon'=>'plug-zap','aliases'=>['API Support'],'description'=>'Provides programmatic API access for application integration.'],
        ['name'=>'Fine-tuning','group'=>'Model Control','icon'=>'sliders-horizontal','aliases'=>[],'description'=>'Supports adapting a model with custom training examples or organization data.'],
        ['name'=>'Embeddings','group'=>'Model Control','icon'=>'binary','aliases'=>[],'description'=>'Produces vector representations for semantic search, clustering and retrieval.'],
        ['name'=>'RAG & Knowledge Bases','group'=>'Research','icon'=>'database-zap','aliases'=>[],'description'=>'Connects models to external knowledge sources for retrieval-augmented responses.'],
        ['name'=>'Memory','group'=>'Agents','icon'=>'memory-stick','aliases'=>[],'description'=>'Retains user, task or session context across interactions.'],
        ['name'=>'Agent Workflows','group'=>'Agents','icon'=>'workflow','aliases'=>[],'description'=>'Plans and executes multi-step tasks with tools, state or autonomous actions.'],
        ['name'=>'Computer Use','group'=>'Agents','icon'=>'monitor-cog','aliases'=>[],'description'=>'Interacts with graphical computer interfaces to complete tasks.'],
        ['name'=>'Browser Automation','group'=>'Agents','icon'=>'globe-2','aliases'=>[],'description'=>'Navigates and interacts with websites or browser-based applications.'],
        ['name'=>'Real-time Streaming','group'=>'Platform','icon'=>'radio-tower','aliases'=>[],'description'=>'Supports low-latency streaming text, audio or multimodal interactions.'],
        ['name'=>'Team Collaboration','group'=>'Platform','icon'=>'users','aliases'=>[],'description'=>'Provides shared workspaces, team controls or collaborative workflows.'],
        ['name'=>'Integrations','group'=>'Platform','icon'=>'blocks','aliases'=>[],'description'=>'Connects with third-party applications, data sources or automation platforms.'],
        ['name'=>'Prompting & Templates','group'=>'Platform','icon'=>'message-square-code','aliases'=>['Prompting'],'description'=>'Provides reusable prompt templates, prompt management or guided prompting tools.'],
    ],

    'use_cases' => [
        ['name'=>'General AI Assistance','icon'=>'bot'],['name'=>'Writing & Editing','icon'=>'pen-line'],['name'=>'Summarization','icon'=>'list-collapse'],
        ['name'=>'Brainstorming','icon'=>'lightbulb'],['name'=>'Question Answering','icon'=>'circle-help'],['name'=>'Document Analysis','icon'=>'file-search'],
        ['name'=>'Web Research','icon'=>'search'],['name'=>'Deep Research','icon'=>'book-open-check'],['name'=>'Academic Research','icon'=>'graduation-cap'],
        ['name'=>'Market Research','icon'=>'chart-no-axes-combined'],['name'=>'Competitive Intelligence','icon'=>'telescope'],['name'=>'Code Completion','icon'=>'code-2'],
        ['name'=>'Debugging','icon'=>'bug'],['name'=>'Code Review','icon'=>'scan-search'],['name'=>'App Prototyping','icon'=>'blocks'],
        ['name'=>'Software Testing','icon'=>'flask-conical'],['name'=>'Image Creation','icon'=>'image-plus'],['name'=>'Image Editing','icon'=>'wand-sparkles'],
        ['name'=>'Logo & Brand Design','icon'=>'palette'],['name'=>'Marketing Creative','icon'=>'megaphone'],['name'=>'Video Creation','icon'=>'clapperboard'],
        ['name'=>'Video Editing','icon'=>'film'],['name'=>'Social Video Production','icon'=>'smartphone'],['name'=>'AI Avatars','icon'=>'scan-face'],
        ['name'=>'Voiceovers','icon'=>'mic-2'],['name'=>'Transcription','icon'=>'audio-lines'],['name'=>'Meeting Notes','icon'=>'notebook-tabs'],
        ['name'=>'Dubbing & Localization','icon'=>'languages'],['name'=>'Music Creation','icon'=>'music'],['name'=>'Podcast Production','icon'=>'podcast'],
        ['name'=>'Workflow Automation','icon'=>'workflow'],['name'=>'Task Automation','icon'=>'list-checks'],['name'=>'Browser Automation','icon'=>'globe-2'],
        ['name'=>'Sales Enablement','icon'=>'badge-dollar-sign'],['name'=>'Sales Outreach','icon'=>'send'],['name'=>'Lead Generation','icon'=>'user-plus'],['name'=>'Customer Support','icon'=>'headphones'],
        ['name'=>'Knowledge Base Support','icon'=>'library-big'],['name'=>'SEO Content','icon'=>'search-check'],['name'=>'Social Media Content','icon'=>'share-2'],
        ['name'=>'Email Writing','icon'=>'mail'],['name'=>'Presentation Creation','icon'=>'presentation'],['name'=>'Data Analysis','icon'=>'chart-column'],['name'=>'Business Intelligence','icon'=>'chart-no-axes-combined'],
        ['name'=>'Spreadsheet Analysis','icon'=>'table-2'],['name'=>'SQL Assistance','icon'=>'database'],['name'=>'Study & Learning','icon'=>'graduation-cap'],
        ['name'=>'Language Learning','icon'=>'languages'],['name'=>'Teaching & Course Creation','icon'=>'book-open'],['name'=>'Accessibility & Read Aloud','icon'=>'accessibility'],
        ['name'=>'Translation & Localization','icon'=>'languages'],['name'=>'Enterprise Knowledge Work','icon'=>'building-2'],
    ],

    'tags' => [
        ['name'=>'Open Source','description'=>'Source code or core implementation is publicly available under an open-source license.'],
        ['name'=>'Free Tier','description'=>'Offers a meaningful free tier or permanently free usage option.'],
        ['name'=>'No-Code','description'=>'Designed for workflows that do not require programming.'],
        ['name'=>'Low-Code','description'=>'Supports visual or assisted development with limited code requirements.'],
        ['name'=>'Developer Focused','description'=>'Primarily designed for developers, engineers or technical teams.'],
        ['name'=>'Enterprise Ready','description'=>'Offers controls or capabilities suited to larger organizations.'],
        ['name'=>'API First','description'=>'API access is a primary product experience or integration path.'],
        ['name'=>'Privacy Focused','description'=>'Emphasizes privacy, local processing or strong data controls.'],
        ['name'=>'Local AI','description'=>'Can run locally, on-device or in a self-hosted environment.'],
        ['name'=>'Self Hosted','description'=>'Supports deployment in an organization-controlled environment.'],
        ['name'=>'Mobile App','description'=>'Offers a dedicated mobile application.'],
        ['name'=>'Browser Extension','description'=>'Offers a browser extension as a primary or companion experience.'],
        ['name'=>'Team Workspace','description'=>'Includes shared workspaces or collaboration features for teams.'],
        ['name'=>'Real-time','description'=>'Supports low-latency or live interactive experiences.'],
        ['name'=>'Multilingual','description'=>'Supports multiple languages for input, output or localization.'],
        ['name'=>'Beginner Friendly','description'=>'Designed to be approachable for non-expert users.'],
        ['name'=>'Professional','description'=>'Built for professional production workflows or specialist users.'],
        ['name'=>'Education','description'=>'Commonly used by students, teachers or learning organizations.'],
        ['name'=>'Research','description'=>'Strong fit for research, evidence synthesis or information discovery.'],
        ['name'=>'Creative','description'=>'Strong fit for visual, audio, video or other creative production.'],
        ['name'=>'Productivity','description'=>'Strong fit for everyday knowledge work and productivity workflows.'],
        ['name'=>'Automation','description'=>'Strong fit for automating repeatable or multi-step workflows.'],
        ['name'=>'Collaboration','description'=>'Includes features designed for multi-user or team collaboration.'],
        ['name'=>'Integrations','description'=>'Offers broad third-party integrations or ecosystem connectivity.'],
        ['name'=>'Legal','description'=>'Designed for legal research, drafting, review or professional legal workflows.'],
        ['name'=>'Healthcare','description'=>'Designed for clinical, healthcare, medical documentation or care workflows.'],
        ['name'=>'Financial Services','description'=>'Designed for finance, investment, banking or financial research workflows.'],
        ['name'=>'Cybersecurity','description'=>'Designed for security operations, threat detection, risk or application security.'],
        ['name'=>'Robotics & Autonomous','description'=>'Designed for robotics, autonomous machines, vehicles or embodied AI systems.'],
    ],

    'legacy_category_defaults' => [
        'AI Chat'=>['subcategory'=>'General AI Assistants','use_cases'=>['General AI Assistance','Question Answering']],
        'AI Assistants'=>['subcategory'=>'General AI Assistants','use_cases'=>['General AI Assistance','Question Answering']],
        'Conversational AI'=>['subcategory'=>'Customer-facing Chatbots','use_cases'=>['Customer Support','General AI Assistance']],
        'AI Coding'=>['subcategory'=>'Code Assistants','use_cases'=>['Code Completion','Debugging']],
        'App Builder'=>['subcategory'=>'App Builders','use_cases'=>['App Prototyping']],
        'Developer Tools'=>['subcategory'=>'AI Developer Platforms','tags'=>['Developer Focused'],'use_cases'=>['App Prototyping']],
        'AI Platform'=>['subcategory'=>'AI Developer Platforms','tags'=>['API First','Enterprise Ready']],
        'AI Infrastructure'=>['subcategory'=>'AI Developer Platforms','tags'=>['API First','Enterprise Ready']],
        'AI Image'=>['subcategory'=>'Image Generators','use_cases'=>['Image Creation']],
        'Image AI'=>['subcategory'=>'Image Generators','use_cases'=>['Image Creation']],
        'Image Editing'=>['subcategory'=>'Image Editors','use_cases'=>['Image Editing']],
        'Design AI'=>['subcategory'=>'Graphic Design','tags'=>['Creative'],'use_cases'=>['Logo & Brand Design','Marketing Creative']],
        'Creative AI'=>['subcategory'=>'Graphic Design','tags'=>['Creative'],'use_cases'=>['Image Creation','Marketing Creative']],
        'AI Video'=>['subcategory'=>'Video Generators','use_cases'=>['Video Creation']],
        'Video AI'=>['subcategory'=>'Video Generators','use_cases'=>['Video Creation']],
        'AI Avatars'=>['subcategory'=>'AI Avatars','use_cases'=>['Video Creation','Social Video Production']],
        'Video Editing'=>['subcategory'=>'Video Editors','use_cases'=>['Video Editing']],
        'Audio & Video AI'=>['subcategory'=>'Video Editors','tags'=>['Creative'],'use_cases'=>['Video Editing','Podcast Production']],
        'AI Writing'=>['subcategory'=>'Writing Assistants','use_cases'=>['Writing & Editing']],
        'Writing AI'=>['subcategory'=>'Writing Assistants','use_cases'=>['Writing & Editing']],
        'AI Voice'=>['subcategory'=>'Voice & Speech Platforms','use_cases'=>['Voiceovers','Transcription']],
        'Voice AI'=>['subcategory'=>'Voice & Speech Platforms','use_cases'=>['Voiceovers','Transcription']],
        'AI Music'=>['subcategory'=>'Music Generators','tags'=>['Creative'],'use_cases'=>['Music Creation']],
        'Music AI'=>['subcategory'=>'Music Generators','tags'=>['Creative'],'use_cases'=>['Music Creation']],
        'AI Search'=>['subcategory'=>'AI Search Engines','use_cases'=>['Web Research']],
        'Research AI'=>['subcategory'=>'Academic Research','tags'=>['Research'],'use_cases'=>['Academic Research','Deep Research']],
        'Enterprise Search'=>['subcategory'=>'Document Research','tags'=>['Enterprise Ready'],'use_cases'=>['Document Analysis','Web Research']],
        'AI Search API'=>['subcategory'=>'AI Search Engines','tags'=>['API First'],'use_cases'=>['Web Research']],
        'Market Intelligence'=>['subcategory'=>'Market Research','tags'=>['Research'],'use_cases'=>['Market Research','Competitive Intelligence']],
        'Medical Research AI'=>['subcategory'=>'Academic Research','tags'=>['Healthcare','Research'],'use_cases'=>['Academic Research','Deep Research']],
        'Legal AI'=>['subcategory'=>'Document Research','tags'=>['Legal','Professional'],'use_cases'=>['Document Analysis','Deep Research']],
        'Finance AI'=>['subcategory'=>'Market Research','tags'=>['Financial Services','Professional'],'use_cases'=>['Market Research']],
        'AI Agents'=>['subcategory'=>'Autonomous Agents','tags'=>['Automation'],'use_cases'=>['Task Automation','Workflow Automation']],
        'AI Automation'=>['subcategory'=>'Workflow Automation','tags'=>['Automation'],'use_cases'=>['Workflow Automation','Task Automation']],
        'Robotics AI'=>['subcategory'=>'Robotics & Autonomous Systems','tags'=>['Robotics & Autonomous'],'use_cases'=>['Task Automation']],
        'Robotics'=>['subcategory'=>'Robotics & Autonomous Systems','tags'=>['Robotics & Autonomous'],'use_cases'=>['Task Automation']],
        'Autonomous AI'=>['subcategory'=>'Robotics & Autonomous Systems','tags'=>['Robotics & Autonomous'],'use_cases'=>['Task Automation']],
        'AI Productivity'=>['subcategory'=>'Documents & Office','tags'=>['Productivity'],'use_cases'=>['Writing & Editing','Document Analysis']],
        'Productivity AI'=>['subcategory'=>'Documents & Office','tags'=>['Productivity'],'use_cases'=>['Writing & Editing','Document Analysis']],
        'Document AI'=>['subcategory'=>'Documents & Office','tags'=>['Productivity'],'use_cases'=>['Document Analysis']],
        'Meeting AI'=>['subcategory'=>'Meeting Assistants','tags'=>['Productivity'],'use_cases'=>['Meeting Notes','Transcription']],
        'Presentation AI'=>['subcategory'=>'Presentations','tags'=>['Productivity'],'use_cases'=>['Presentation Creation']],
        'Healthcare AI'=>['subcategory'=>'Healthcare & Clinical AI','tags'=>['Healthcare','Professional'],'use_cases'=>['Data Analysis','Document Analysis']],
        'Enterprise AI'=>['subcategory'=>'Enterprise AI Platforms','tags'=>['Enterprise Ready','Professional'],'use_cases'=>['Data Analysis','Business Intelligence']],
        'Cybersecurity AI'=>['subcategory'=>'Security & Risk Analytics','tags'=>['Cybersecurity','Enterprise Ready'],'use_cases'=>['Data Analysis']],
        'AI Security'=>['subcategory'=>'Security & Risk Analytics','tags'=>['Cybersecurity'],'use_cases'=>['Data Analysis']],
        'Marketing AI'=>['subcategory'=>'Marketing Automation','tags'=>['Professional'],'use_cases'=>['Marketing Creative','Writing & Editing']],
        'Sales AI'=>['subcategory'=>'Sales Assistants','tags'=>['Professional'],'use_cases'=>['Sales Outreach','Meeting Notes']],
        'Customer Support AI'=>['subcategory'=>'Support Chatbots','use_cases'=>['Customer Support']],
        'Contact Center AI'=>['subcategory'=>'Contact Center AI','use_cases'=>['Customer Support','Transcription']],
        'Voice Agents'=>['subcategory'=>'Contact Center AI','use_cases'=>['Customer Support','Voiceovers']],
    ],

    'content_topics' => [
        ['name'=>'Guides & Tutorials','slug'=>'guides-tutorials','legacy'=>['Guide'],'description'=>'Practical guides, tutorials and workflows for using AI tools and models effectively.'],
        ['name'=>'Model Releases','slug'=>'model-releases','legacy'=>['New Model'],'description'=>'Coverage and analysis of newly released AI models, versions and capabilities.'],
        ['name'=>'Product Updates','slug'=>'product-updates','legacy'=>['Product Update'],'description'=>'Important feature releases and product changes across AI tools and platforms.'],
        ['name'=>'Pricing & Plans','slug'=>'pricing-plans','legacy'=>['Pricing Change'],'description'=>'Analysis of AI pricing changes, subscriptions, API costs and plan updates.'],
        ['name'=>'Research & Papers','slug'=>'research-papers','legacy'=>['Research'],'description'=>'AI research papers, technical findings and evidence-driven analysis.'],
        ['name'=>'Benchmarks & Evaluations','slug'=>'benchmarks-evaluations','legacy'=>['Benchmark'],'description'=>'Model and tool benchmark results, evaluations, testing methodology and performance analysis.'],
        ['name'=>'Industry Analysis','slug'=>'industry-analysis','legacy'=>[],'description'=>'Analysis of AI markets, companies, adoption trends and competitive dynamics.'],
        ['name'=>'Opinion & Commentary','slug'=>'opinion-commentary','legacy'=>['Opinion'],'description'=>'Editorial perspectives and informed commentary about AI products, policy and industry developments.'],
        ['name'=>'How-To','slug'=>'how-to','legacy'=>[],'description'=>'Step-by-step practical instructions for completing tasks with AI.'],
        ['name'=>'News Analysis','slug'=>'news-analysis','legacy'=>[],'description'=>'Context and interpretation for important AI news and ecosystem developments.'],
    ],

    'legacy_subcategory_map' => [
        'AI Assistant' => ['category'=>'chat-assistants','subcategory'=>'General AI Assistants'],
        'Image Generator' => ['category'=>'image-design','subcategory'=>'Image Generators'],
        'Video Generator' => ['category'=>'video-animation','subcategory'=>'Video Generators'],
        'Code Assistant' => ['category'=>'coding-development','subcategory'=>'Code Assistants'],
        'Writing Assistant' => ['category'=>'writing-content','subcategory'=>'Writing Assistants'],
        'Voice Generator' => ['category'=>'voice-audio','subcategory'=>'Text to Speech'],
        'Research Assistant' => ['category'=>'search-research','subcategory'=>'Deep Research'],
        'Developer Platform' => ['category'=>'coding-development','subcategory'=>'Developer Agents'],
        'Knowledge Assistant' => ['category'=>'chat-assistants','subcategory'=>'Knowledge Assistants'],
        'Creative Suite' => ['category'=>'image-design','subcategory'=>'Graphic Design'],
    ],

    'use_case_inference' => [
        'Text Generation' => ['Writing & Editing','Summarization','Brainstorming'],
        'Reasoning' => ['General AI Assistance','Question Answering'],
        'Web Browsing & Search' => ['Web Research','Market Research'],
        'Deep Research' => ['Deep Research','Academic Research','Competitive Intelligence'],
        'Document & PDF Analysis' => ['Document Analysis','Study & Learning'],
        'Image Generation' => ['Image Creation','Marketing Creative','Logo & Brand Design'],
        'Image Editing' => ['Image Editing','Marketing Creative'],
        'Video Generation' => ['Video Creation','Social Video Production'],
        'Video Editing' => ['Video Editing','Social Video Production'],
        'Code Generation' => ['Code Completion','App Prototyping'],
        'Code Review & Debugging' => ['Debugging','Code Review'],
        'Speech to Text' => ['Transcription','Meeting Notes'],
        'Text to Speech' => ['Voiceovers','Accessibility & Read Aloud'],
        'Voice Cloning' => ['Voiceovers','Dubbing & Localization'],
        'Music Generation' => ['Music Creation','Podcast Production'],
        'Agent Workflows' => ['Workflow Automation','Task Automation'],
        'Browser Automation' => ['Browser Automation','Workflow Automation'],
    ],
];
