@extends('layouts.admin')
@section('title', 'AI Reviews')
@section('content')
<x-page-header title="AI Review Management" subtitle="{{ $counts['all'] }} total reviews · {{ $counts['pending'] }} awaiting moderation" :breadcrumb="['Content','Reviews']"><x-slot:actions><a href="{{ route('admin.content.reviews.editor') }}" class="btn btn-primary btn-sm"><i data-lucide="plus"></i> Add Editorial Review</a></x-slot:actions></x-page-header>
@if(session('status'))<div class="alert alert-success" style="margin-bottom:16px;">{{ session('status') }}</div>@endif
<div class="tabs"><a class="tab {{ !request('status')?'is-active':'' }}" href="{{ route('admin.content.reviews.index') }}">All {{ $counts['all'] }}</a><a class="tab {{ request('status')==='pending'?'is-active':'' }}" href="{{ route('admin.content.reviews.index',['status'=>'pending']) }}">Pending {{ $counts['pending'] }}</a><a class="tab {{ request('status')==='published'?'is-active':'' }}" href="{{ route('admin.content.reviews.index',['status'=>'published']) }}">Published {{ $counts['published'] }}</a><a class="tab {{ request('status')==='flagged'?'is-active':'' }}" href="{{ route('admin.content.reviews.index',['status'=>'flagged']) }}">Flagged {{ $counts['flagged'] }}</a></div>
<form method="GET" class="filter-bar"><input type="hidden" name="status" value="{{ request('status') }}"><div class="input-search" style="background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-sm);padding:8px 12px;"><i data-lucide="search"></i><input name="search" value="{{ request('search') }}" placeholder="Search reviews or tools..."></div><select class="select" name="tool_id"><option value="">All tools</option>@foreach($tools as $tool)<option value="{{ $tool->id }}" @selected(request('tool_id')==$tool->id)>{{ $tool->name }}</option>@endforeach</select><select class="select" name="type"><option value="">All types</option><option value="user" @selected(request('type')==='user')>User</option><option value="editorial" @selected(request('type')==='editorial')>Editorial</option></select><select class="select" name="rating"><option value="">Any rating</option><option value="4" @selected(request('rating')==='4')>4.0+</option><option value="3" @selected(request('rating')==='3')>3.0+</option></select><button class="btn btn-secondary btn-sm">Filter</button></form>
<div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Tool</th><th>Reviewer</th><th>Type</th><th>Rating</th><th>Verdict</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>@forelse($reviews as $review)<tr><td><b>{{ $review->tool->name ?? '—' }}</b></td><td class="text-sub">{{ $review->user->name ?? ($review->review_type==='editorial'?'Editorial Team':'Guest') }}</td><td><span class="badge badge-neutral">{{ ucfirst($review->review_type ?? 'user') }}</span></td><td><b>{{ number_format((float)$review->rating,1) }}</b>/5</td><td class="text-sub">{{ \Illuminate\Support\Str::limit($review->verdict ?: $review->body,55) ?: '—' }}</td><td><x-status-badge status="{{ ucfirst($review->status) }}" type="{{ $review->status==='published'?'pos':($review->status==='flagged'?'neg':'warn') }}" /></td><td class="cell-sub">{{ $review->created_at->format('M j, Y') }}</td><td><div class="flex gap-8"><a href="{{ route('admin.content.reviews.show',$review->id) }}" class="icon-btn"><i data-lucide="eye"></i></a>@if($review->status!=='published')<form method="POST" action="{{ route('admin.content.reviews.approve',$review->id) }}">@csrf<button class="icon-btn" title="Approve"><i data-lucide="check"></i></button></form>@endif @if($review->status!=='flagged')<form method="POST" action="{{ route('admin.content.reviews.flag',$review->id) }}">@csrf<button class="icon-btn" title="Flag"><i data-lucide="flag"></i></button></form>@endif</div></td></tr>@empty<tr><td colspan="8" class="text-sub" style="text-align:center;padding:32px;">No reviews match these filters.</td></tr>@endforelse</tbody></table></div><div class="pager"><span>Showing {{ $reviews->firstItem() ?? 0 }}–{{ $reviews->lastItem() ?? 0 }} of {{ $reviews->total() }}</span><div class="pager-btns">{{ $reviews->links() }}</div></div></div>
@endsection
