@extends('frontend.layouts.app')
@section('title',$subcategory->meta_title ?: $subcategory->name.' AI Tools — AI Hub')
@section('meta_description',$subcategory->meta_description ?: $subcategory->short_description)
@push('head')<link rel="canonical" href="{{ route('categories.subcategories.show',[$category,$subcategory]) }}"><meta name="robots" content="{{ ($tools->total() + $models->count()) > 0 ? 'index,follow,max-image-preview:large' : 'noindex,follow' }}"><script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'CollectionPage','name'=>$subcategory->name,'description'=>$subcategory->description ?: $subcategory->short_description,'url'=>route('categories.subcategories.show',[$category,$subcategory])], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>@endpush
@push('styles')<link rel="stylesheet" href="{{ asset('css/frontend/discovery.css') }}">@endpush
@section('content')
<section class="category-detail-hero"><div class="category-detail-inner"><div class="category-hero-main"><a class="breadcrumb-link" href="{{ route('categories.show',$category) }}"><i data-lucide="arrow-left"></i> {{ $category->name }}</a><span class="eyebrow"><i data-lucide="git-branch"></i> AI Subcategory</span><h1>{{ $subcategory->name }}</h1><p>{{ $subcategory->description ?: $subcategory->short_description }}</p><div class="category-hero-actions"><a class="primary-action" href="#subcategory-tools">Explore tools <i data-lucide="arrow-down"></i></a><a class="secondary-action" href="{{ route('search.index',['q'=>$subcategory->name]) }}">Search this topic <i data-lucide="search"></i></a></div></div><div class="category-stat-board"><span><strong>{{ number_format($tools->total()) }}</strong><small>Published tools</small></span><span><strong>{{ number_format($models->count()) }}</strong><small>Related models</small></span></div></div></section>
<div class="discovery-page category-detail-page"><section id="subcategory-tools" class="result-section"><div class="section-bar category-tools-bar"><div><span class="section-icon"><i data-lucide="bot"></i></span><h2>Top {{ $subcategory->name }} Tools</h2><small>{{ number_format($tools->total()) }} products</small></div><form method="get" class="sort-form"><label for="subcategory-sort">Sort</label><select id="subcategory-sort" name="sort" onchange="this.form.submit()"><option value="top" @selected($sort==='top')>Top rated</option><option value="popular" @selected($sort==='popular')>Most popular</option><option value="newest" @selected($sort==='newest')>Newest</option></select></form></div>@if($tools->count())<div class="category-tool-grid">@foreach($tools as $tool)<article class="category-tool-card"><div class="tool-card-head"><img src="{{ $tool->logo_url }}" alt="{{ $tool->name }} logo"><div><small>{{ $tool->company?->name ?? 'AI Tool' }}</small><h3><a href="{{ route('tools.show',$tool) }}">{{ $tool->name }}</a></h3></div><span class="rating-pill"><i data-lucide="star"></i>{{ number_format((float)$tool->rating,1) }}</span></div><p>{{ \Illuminate\Support\Str::limit($tool->short_description ?: $tool->description,125) }}</p><div class="tool-card-foot"><span>{{ $category->name }}</span><a href="{{ route('tools.show',$tool) }}">View tool <i data-lucide="arrow-right"></i></a></div></article>@endforeach</div><div class="category-pagination">{{ $tools->links() }}</div>@else<div class="inline-empty"><i data-lucide="package-open"></i><div><h3>No published tools yet</h3><p>This subcategory is ready for future listings.</p></div></div>@endif</section>@if($models->isNotEmpty())<section class="result-section"><div class="section-bar"><div><span class="section-icon cyan"><i data-lucide="cpu"></i></span><h2>Related AI Models</h2></div></div><div class="category-model-grid">@foreach($models as $model)<a class="category-model-card" href="{{ route('models.show',$model) }}"><img src="{{ $model->logo_url }}" alt="{{ $model->name }}"><div><small>{{ $model->company?->name }}</small><h3>{{ $model->name }}</h3><span>{{ $model->context_window ?: '—' }}</span></div><b>{{ $model->benchmark_score !== null ? number_format((float)$model->benchmark_score,1) : '—' }}</b></a>@endforeach</div></section>@endif@if($relatedSubcategories->isNotEmpty())<section class="related-category-strip"><div><span class="eyebrow"><i data-lucide="compass"></i> Keep exploring</span><h2>More in {{ $category->name }}</h2></div><div class="related-category-links">@foreach($relatedSubcategories as $related)<a href="{{ route('categories.subcategories.show',[$category,$related]) }}"><span>{{ $related->name }}</span><small>{{ $related->tools_count }} tools</small><i data-lucide="arrow-up-right"></i></a>@endforeach</div></section>@endif</div>
@endsection
